Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Placement_Content__c</fullName>
                    <label>Placement Content</label>
                </value>
                <value>
                    <fullName>Placement_Library__c</fullName>
                    <label>Placement Library</label>
                </value>
                <value>
                    <fullName>Placement_Content_Detail__c</fullName>
                    <label>Placement Content Detail</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DGTL_Bangalore_Commerce_Services</fullName>
                    <label>Bangalore Commerce Services</label>
                </value>
                <value>
                    <fullName>DGTL_Commerce_Operations</fullName>
                    <label>Commerce Operations</label>
                </value>
                <value>
                    <fullName>DGTL_Copy_Writer</fullName>
                    <label>Copy Writer</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Design</fullName>
                    <label>Creative Design</label>
                </value>
                <value>
                    <fullName>DGTL_Digital_Producers</fullName>
                    <label>Digital Producers</label>
                </value>
                <value>
                    <fullName>DGTL_Merchandiser</fullName>
                    <label>Merchandiser</label>
                </value>
                <value>
                    <fullName>DGTL_Offer_Management</fullName>
                    <label>Offer Management</label>
                </value>
                <value>
                    <fullName>DGTL_Angelcard</fullName>
                    <label>Angelcard</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Operations</fullName>
                    <isActive>false</isActive>
                    <label>Creative Operations</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserOrProfileId__c</fullName>
        <label>UserOrProfileId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Writable_Fields__c</fullName>
        <label>Writable Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Object_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Name</fullName>
                </value>
                <value>
                    <fullName>Placement_layout__c</fullName>
                    <label>Placement layout</label>
                </value>
                <value>
                    <fullName>Placement_library__c</fullName>
                    <label>Placement library</label>
                </value>
                <value>
                    <fullName>Image__c</fullName>
                    <label>Image</label>
                </value>
                <value>
                    <fullName>Link__c</fullName>
                    <label>Link</label>
                </value>
                <value>
                    <fullName>Main_Message__c</fullName>
                    <label>Main Message</label>
                </value>
                <value>
                    <fullName>Offer_Type__c</fullName>
                    <label>Offer Type</label>
                </value>
                <value>
                    <fullName>Page_Name__c</fullName>
                    <label>Page Name</label>
                </value>
                <value>
                    <fullName>Position__c</fullName>
                    <label>Position</label>
                </value>
                <value>
                    <fullName>Projected__c</fullName>
                    <label>Projected</label>
                </value>
                <value>
                    <fullName>Shot_Number__c</fullName>
                    <label>Shot Number</label>
                </value>
                <value>
                    <fullName>Style_Info__c</fullName>
                    <label>Style Info</label>
                </value>
                <value>
                    <fullName>S_No__c</fullName>
                    <label>S No</label>
                </value>
                <value>
                    <fullName>Copy_Image__c</fullName>
                    <label>Copy Image</label>
                </value>
                <value>
                    <fullName>Active__c</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>approval_status__c</fullName>
                    <label>approval status</label>
                </value>
                <value>
                    <fullName>Content_Type__c</fullName>
                    <label>Content Type</label>
                </value>
                <value>
                    <fullName>layout_type__c</fullName>
                    <label>layout type</label>
                </value>
                <value>
                    <fullName>theme__c</fullName>
                    <label>theme</label>
                </value>
                <value>
                    <fullName>textbox_width__c</fullName>
                    <label>textbox width</label>
                </value>
                <value>
                    <fullName>textbox_background_color__c</fullName>
                    <label>textbox background color</label>
                </value>
                <value>
                    <fullName>text_box_opacity__c</fullName>
                    <label>text box opacity</label>
                </value>
                <value>
                    <fullName>headline_color__c</fullName>
                    <label>headline color</label>
                </value>
                <value>
                    <fullName>copy_color__c</fullName>
                    <label>copy color</label>
                </value>
                <value>
                    <fullName>ImagePath__c</fullName>
                    <label>ImagePath</label>
                </value>
                <value>
                    <fullName>image_link__c</fullName>
                    <label>image link</label>
                </value>
                <value>
                    <fullName>image_map_path__c</fullName>
                    <label>image map path</label>
                </value>
                <value>
                    <fullName>cta__c</fullName>
                    <label>cta</label>
                </value>
                <value>
                    <fullName>details_link__c</fullName>
                    <label>details link</label>
                </value>
                <value>
                    <fullName>video_file_path__c</fullName>
                    <label>video file path</label>
                </value>
                <value>
                    <fullName>Placement_Content_Detail__c</fullName>
                    <label>Placement Content Detail</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/DGTL_ErrorMessages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to display error messages in Digital application</description>
    <label>DGTL_ErrorMessages</label>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error_Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>TEXT(Placement_Layout__r.Brands__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Placement_Content__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/User.object
<CustomObject>
    <fields>
        <fullName>DGTL_Profile__c</fullName>
        <label>DGTL Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DGTL_Bangalore_Commerce_Services</fullName>
                    <label>Bangalore Commerce Services</label>
                </value>
                <value>
                    <fullName>DGTL_Commerce_Operations</fullName>
                    <label>Commerce Operations</label>
                </value>
                <value>
                    <fullName>DGTL_Copy_Writer</fullName>
                    <label>Copy Writers</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Design</fullName>
                    <label>Creative Design</label>
                </value>
                <value>
                    <fullName>DGTL_Digital_Producers</fullName>
                    <label>Digital Producers</label>
                </value>
                <value>
                    <fullName>DGTL_Merchandiser</fullName>
                    <label>Merchandiser</label>
                </value>
                <value>
                    <fullName>DGTL_Offer_Management</fullName>
                    <label>Offer Management</label>
                </value>
                <value>
                    <fullName>DGTL_Angelcard</fullName>
                    <label>Angelcard</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Operations</fullName>
                    <isActive>false</isActive>
                    <label>Creative Operations</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_Util.cls
public class DGTL_Util {
    
   /* public static Map<String,List<sObject>> getConvertedData(Map<String,List<sObject>> dataMap){
        Map<String,Map<String,DGTL_Access_Management__c>> accessMngMap = new Map<String,Map<String,DGTL_Access_Management__c>>();
        Id recordTypeId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        Map<String,List<sObject>> convertedDataMap = new Map<String,List<sObject>>();
        Map<String,List<String>> fieldsToIgnoreMap = getfieldsToIgnoreOnConversion();
        String digitalProfile = '';

        try{
            digitalProfile = [SELECT DGTL_Profile__c FROM User WHERE Id = :UserInfo.getUserId()].DGTL_Profile__c; // get current user digital profile
        }catch(QueryException qe){ System.debug('QueryException caught: '+qe.getMessage()); }
        
        for(DGTL_Access_Management__c accMang : [SELECT Brands__c,Object_Name__c,Writable_Fields__c FROM DGTL_Access_Management__c 
                                                 WHERE  RecordTypeId = :recordTypeId
                                                 AND (Object_Name__c IN :dataMap.keySet()) 
                                                 AND Writable_Fields__c != null 
                                                 AND (Team__c = :digitalProfile OR UserOrProfileId__c = :UserInfo.getUserId() 
                                                      OR UserOrProfileId__c = :UserInfo.getProfileId()) 
                                                 ORDER BY CreatedDate DESC  ])
        {
            if(!accessMngMap.containsKey(accMang.Brands__c)) accessMngMap.put(accMang.Brands__c, new Map<String,DGTL_Access_Management__c>());
            if(!accessMngMap.get(accMang.Brands__c).containsKey(accMang.Object_Name__c)) accessMngMap.get(accMang.Brands__c).put(accMang.Object_Name__c,accMang);
        }
        
        for(String objName : dataMap.keySet()){
            List<sObject> sObjList = new List<sObject>();
            SObjectType sobjMap = ((SObject)(Type.forName('Schema.'+objName).newInstance())).getSObjectType();
            DescribeSObjectResult fieldType = sobjMap.getDescribe();
            for(sObject sObj : dataMap.get(objName)){
                
                if(sObj.get('Id') != null){
                    String brand = String.valueOf(sObj.get('Brand__c')); // need to modify for generic api names
                    System.debug('brand----'+brand);
                    if(accessMngMap.containsKey(brand) && accessMngMap.get(brand).containsKey(objName)){
                        sObject convertedSObj = Id.valueOf(String.valueOf(sObj.get('Id'))).getSObjectType().newSObject();
                        convertedSObj.put('Id', sObj.get('Id'));
                        
                        // put the value of all the fields which needs to be ignored by access management permission
                        if(fieldsToIgnoreMap.containsKey(objName)){
                            for(String ignoreFld : fieldsToIgnoreMap.get(objName)){
                                string fielddatatype = string.valueof(fieldType.fields.getMap().get(ignoreFld).getDescribe().getType());
                                if(sObj.get(ignoreFld) == null &&  fielddatatype == 'BOOLEAN')
                                convertedSObj.put(ignoreFld, false);
                                else
                                convertedSObj.put(ignoreFld, sObj.get(ignoreFld));
                            }
                        }
                        
                        // put the value of all the writeable fields from access management
                        for(String str : accessMngMap.get(brand).get(objName).Writable_Fields__c.split(';')){
                            string fielddatatype = string.valueof(fieldType.fields.getMap().get(str).getDescribe().getType());
                            if(sObj.get(str) == null && fielddatatype == 'BOOLEAN')
                               convertedSObj.put(str, false);
                             else
                                convertedSObj.put(str, sObj.get(str));
                        }
                        
                        sObjList.add(convertedSObj); 
                    }else{                        
                       // throw new DGTL_Exception(sObj.get('Name') + ' - ' +DGTL_ErrorMessages__c.getValues('DGTL_Main_NoAccessMang').Error_Message__c);
                    }
                    
                }else{
                    sObjList.add(sObj); // new record doesn't need permission conversion
                }
            }
            convertedDataMap.put(objName,sObjList);
        }
        
        return convertedDataMap;
    }
    
    public static Map<String,List<String>> getfieldsToIgnoreOnConversion(){
        Map<String,List<String>> fieldsToIgnoreMap = new Map<String,List<String>>();
        Schema.FieldSet fs = Schema.SObjectType.Placement_Content__c.fieldSets.Fields_To_Ignore;
        Schema.FieldSet fs2 = Schema.SObjectType.Placement_Content_Detail__c.fieldSets.Fields_To_Ignore;
        
        for(Schema.FieldSetMember f : fs.getFields()) {
            if(!fieldsToIgnoreMap.containsKey('Placement_Content__c')) fieldsToIgnoreMap.put('Placement_Content__c', new List<String>());
            fieldsToIgnoreMap.get('Placement_Content__c').add(f.getFieldPath());   
        }
       
        for(Schema.FieldSetMember f2 : fs2.getFields()) {
            if(!fieldsToIgnoreMap.containsKey('Placement_Content_Detail__c')) fieldsToIgnoreMap.put('Placement_Content_Detail__c', new List<String>());
            fieldsToIgnoreMap.get('Placement_Content_Detail__c').add(f2.getFieldPath());   
        }
        
        return fieldsToIgnoreMap;
    }*/
    
    public static String getFloorsetName(String floorsetId){
        try{
            return [SELECT Name FROM DGTL_Floorset_Plan__c WHERE Id = :floorsetId].Name;
        }catch(Exception e){
            throw new AuraException(e.getMessage());
        }
    }
    
    public static Map<String,String> getReadOnlyPickListFields(String objName){
        Map<String,String> fieldLabelMap = new Map<String,String>();
        Set<String> objFields = new Set<String>();
        
        for(String str : Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap().keySet()){
            objFields.add(str.toLowerCase());
        }
        
        Schema.DescribeFieldResult fieldResult = DGTL_Access_Management__c.Read_Only_Fields__c.getDescribe();
        for(Schema.PicklistEntry pickListVal : fieldResult.getPicklistValues()){
            String value = pickListVal.getValue();
            if(pickListVal.isActive() && objFields.contains(value.toLowerCase()))
                fieldLabelMap.put(value,pickListVal.getLabel());
        }

        return fieldLabelMap;
    }
    
    public static List<Schema.FieldSetMember> getFieldSetValues(String fieldSetName, String objectName){
        Schema.DescribeSObjectResult DescribeSObjectResultObj =  Schema.getGlobalDescribe().get(objectName).getDescribe();
        Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
        return fieldSetObj.getFields(); 
    } 

}