Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_No__c</fullName>
        <formula>IF(CONTAINS( TEXT(Time__c) , &#39;AM&#39;), 
IF(LEN(TEXT(Time__c))=5, 
IF(CONTAINS( TEXT(Time__c) , &#39;12&#39;),0,VALUE(LEFT(TEXT(Time__c),2))), 
VALUE(LEFT(TEXT(Time__c),1)) 
), 
IF(LEN(TEXT(Time__c))=5, 
VALUE(LEFT(TEXT(Time__c),2))+12, 
VALUE(LEFT(TEXT(Time__c),1))+12 
) 
) * 60 + VALUE(Text(Minute__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Placement_Content__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Floorset Plan</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Brands__c</field>
                <operation>equals</operation>
                <valueField>DGTL_Floorset_Plan__c.Brands__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_No__c</fullName>
        <formula>Floorset_Plan__r.Time_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_CloneFloorsetHierarchy.cls
public class DGTL_CloneFloorsetHierarchy {
    
    @AuraEnabled
    public static DGTL_FloorsetHierarchyCloneWrap getPreviousFloorsetPlan(String floorsetId){
        DGTL_CloneFloorsetHierarchy.DGTL_FloorsetHierarchyCloneWrap wrapper = new DGTL_CloneFloorsetHierarchy.DGTL_FloorsetHierarchyCloneWrap();
        DGTL_Floorset_Plan__c previousFloorset;
        List<Placement_Layout__c> filteredPageType = new List<Placement_Layout__c>();
        Map<String,Placement_Layout__c> pageTypes = new Map<String,Placement_Layout__c>();
        Map<String,Placement_Layout__c> currentPageTypes = new Map<String,Placement_Layout__c>();
        DGTL_Floorset_Plan__c currentFloorset = [SELECT Id,Brands__c,Date__c,Time_No__c 
                                                 FROM DGTL_Floorset_Plan__c 
                                                 WHERE Id=:floorsetId];
        
        try{
            previousFloorset = [SELECT Id,Name FROM DGTL_Floorset_Plan__c 
                                WHERE Brands__c=:currentFloorset.Brands__c 
                                AND Date__c <= :currentFloorset.Date__c 
                                AND Id != :currentFloorset.Id 
                                ORDER BY Date__c DESC, Time_No__c DESC LIMIT 1]; 
            
            //------------ for Page Types Check boxes
            currentPageTypes = getAllPageTypes(floorsetId);	
            pageTypes = getAllPageTypes(previousFloorset.Id);
            
            for(String page : pageTypes.keySet()){
                if(currentPageTypes.get(page) == null)
                    filteredPageType.add(pageTypes.get(page));
            }
            //------------ for Page Types Check boxes
            
        }catch(QueryException qe){
            throw new AuraException('No previous floorset found!');
        }catch(Exception e){
            throw new AuraException(e.getMessage());
        }
        wrapper.obj_Floorset = previousFloorset;
        wrapper.pageTypes = pageTypes;
        wrapper.list_filteredPageType = filteredPageType;
        return wrapper;
    }
    
    // get all the Layouts by page types and Device Type for a Floorset
    public static Map<String,Placement_Layout__c> getAllPageTypes(String floorsetId){
        Map<String,Placement_Layout__c> map_pageTypes = new Map<String,Placement_Layout__c>();
        List<Placement_Layout__c> pLayoutList = new List<Placement_Layout__c>();
        String typeStr = 'Layout';
        String query = 'SELECT Id,';
        
        for(Schema.SObjectField fld: Placement_Layout__c.sObjectType.getDescribe().fields.getMap().values()){
            query +=  fld.getDescribe().isCreateable() ? fld.getDescribe().getName()+',' : '';
        }
        query = query.removeEnd(',');
        query += ' FROM Placement_Layout__c WHERE Floorset_Plan__c = :floorsetId AND Is_Deleted__c = false';
        query += ' AND Type__c  =:typeStr ORDER BY Page_Types__c';
        try{
            pLayoutList = Database.query(query);
        }catch(QueryException qe){
            System.debug('*****QueryException****'+qe.getMessage());
        }
        
        for(Placement_Layout__c curLayout : pLayoutList){
            map_pageTypes.put(curLayout.Page_Types__c +'-'+curLayout.Device_Type__c,curLayout);
        }
        return map_pageTypes;
    }
    
    @AuraEnabled
    public static void cloneFloorsetChildHierarchy(String previousFloorsetId, String floorsetId, List<Placement_Layout__c> pLayoutListToSelClone){
        //get all the child layouts for the given floorset plan id
        List<Placement_Layout__c> pLayoutListToClone = new List<Placement_Layout__c>();
        
        for(Placement_Layout__c pl : pLayoutListToSelClone){ //assign current Floorset Id for the layouts to be cloned
            pl.Floorset_Plan__c = floorsetId;
            pLayoutListToClone.add(pl);
        }
        
        if(pLayoutListToClone.size() > 0){
            // clone layouts, contents, content details and placementKOD
            Map<String,List<String>> childsToCloneMap = new Map<String,List<String>>();
            childsToCloneMap.put('Placement_Layout__c', new List<String>{'Placement_Content__c'});
            childsToCloneMap.put('Placement_Content__c', new List<String>{'Placement_Content_Detail__c'});
            
            try{
                DGTL_GenericMultiLevelClone.deepCloneBatched(pLayoutListToClone,childsToCloneMap,null);
            }catch(Exception e){
				if(!Test.isRunningTest()){
				    throw new AuraException(e.getMessage());
				}
            }
            
        }else{
            throw new AuraException('No Layouts Found!');
        }
        
    }
    
    // get all the placement layouts for the given floorset plan Id
   /* private static List<Placement_Layout__c> getChildLayouts(String floorsetId){
        List<Placement_Layout__c> pLayoutList = new List<Placement_Layout__c>();
        String query = 'SELECT Id,';
        for(Schema.SObjectField fld: Placement_Layout__c.sObjectType.getDescribe().fields.getMap().values()){
            query +=  fld.getDescribe().isCreateable() ? fld.getDescribe().getName()+',' : '';
        }
        query = query.removeEnd(',');
        query += ' FROM Placement_Layout__c WHERE Floorset_Plan__c = :floorsetId AND Is_Deleted__c = false';
        
        try{
           pLayoutList = Database.query(query);
        }catch(QueryException qe){
            System.debug('*****QueryException****'+qe.getMessage());
        }
        
        return pLayoutList;
    }*/
    
    
    public class DGTL_FloorsetHierarchyCloneWrap
    {
        @AuraEnabled public DGTL_Floorset_Plan__c obj_Floorset {get;set;}
        @AuraEnabled public  Map<String,Placement_Layout__c> pageTypes {get;set;}
        @AuraEnabled public List<Placement_Layout__c> list_filteredPageType {get;set;}
        
        public DGTL_FloorsetHierarchyCloneWrap()
        {
            DGTL_Floorset_Plan__c obj_Floorset = NEW DGTL_Floorset_Plan__c();
            pageTypes = new Map<String,Placement_Layout__c>();
            list_filteredPageType= new List<Placement_Layout__c>();
        }
    }

}