Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Name__c</fullName>
        <label>Test Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Types</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_Main_AddToLibraryTest.cls
/************************************************************
Name          : DGTL_Main_AddToLibraryTest
Description   : Test Class for DGTL_Main_AddToLibrary      
*************************************************************/
@isTest
public class DGTL_Main_AddToLibraryTest {
     @TestSetup
        static void datasetup(){
            Test.startTest();
            list<DGTL_Floorset_Plan__c> list_Floorset = new list<DGTL_Floorset_Plan__c>();
            list_Floorset.add(DGTL_TestDataFactory.createFloorsetPlan('VS',date.today(),'5 AM','Update'));
            list_Floorset.add(DGTL_TestDataFactory.createFloorsetPlan('VS',date.today()+4,'5 AM','Update'));
            insert  list_Floorset;
            insert DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1, 'VS', 'Home Page', '5 AM', '5 AM', 'Desktop', 'Approved', 'Non Offer', 'mainMsg');
            insert DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',list_Floorset[1].Id, 'Layout');
            Test.stopTest();
        }
        static testmethod void AddToLibrary(){
            Test.startTest(); 
            Placement_Library__c lib = [select id from Placement_Library__c limit 1];
            Placement_Layout__c lay = [select id,Test_Name__c from Placement_Layout__c where Page_Types__c = 'Home Page' limit 1];
            DGTL_Main_AddToLibrary.fetchlibFields();
            DGTL_Main_AddToLibrary.createLibAndContent(string.valueOf(lib.Id), string.valueOf(lay.Id));
            DGTL_Main_AddToLibrary.createLibAndContent(string.valueOf(lay.Id),string.valueOf(lib.Id));
            Test.stopTest();
        }

}