Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_Schedule_time__c</fullName>
        <label>Last Schedule time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Interval_Time__c</fullName>
        <label>Schedule Interval Time(For Notification)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 mins</fullName>
                </value>
                <value>
                    <fullName>60 mins</fullName>
                </value>
                <value>
                    <fullName>2 hrs</fullName>
                </value>
                <value>
                    <fullName>3 hrs</fullName>
                </value>
                <value>
                    <fullName>4 hrs</fullName>
                </value>
                <value>
                    <fullName>5 hrs</fullName>
                </value>
                <value>
                    <fullName>6 hrs</fullName>
                </value>
                <value>
                    <fullName>7 hrs</fullName>
                </value>
                <value>
                    <fullName>8 hrs</fullName>
                </value>
                <value>
                    <fullName>9 hrs</fullName>
                </value>
                <value>
                    <fullName>10 hrs</fullName>
                </value>
                <value>
                    <fullName>11 hrs</fullName>
                </value>
                <value>
                    <fullName>12 hrs</fullName>
                </value>
                <value>
                    <fullName>13 hrs</fullName>
                </value>
                <value>
                    <fullName>14 hrs</fullName>
                </value>
                <value>
                    <fullName>24 hrs</fullName>
                </value>
                <value>
                    <fullName>1.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>1.5 hrs</label>
                </value>
                <value>
                    <fullName>10.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>10.5 hrs</label>
                </value>
                <value>
                    <fullName>11.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>11.5 hrs</label>
                </value>
                <value>
                    <fullName>12.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>12.5 hrs</label>
                </value>
                <value>
                    <fullName>13.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>13.5 hrs</label>
                </value>
                <value>
                    <fullName>2.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>2.5 hrs</label>
                </value>
                <value>
                    <fullName>3.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>3.5 hrs</label>
                </value>
                <value>
                    <fullName>4.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>4.5 hrs</label>
                </value>
                <value>
                    <fullName>45 mins</fullName>
                    <isActive>false</isActive>
                    <label>45 mins</label>
                </value>
                <value>
                    <fullName>5.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>5.5 hrs</label>
                </value>
                <value>
                    <fullName>6.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>6.5 hrs</label>
                </value>
                <value>
                    <fullName>7.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>7.5 hrs</label>
                </value>
                <value>
                    <fullName>8.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>8.5 hrs</label>
                </value>
                <value>
                    <fullName>9.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>9.5 hrs</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Notification</fullName>
        <active>true</active>
        <label>Notification</label>
    </recordTypes>
</CustomObject>

Digital/classes/DGTL_AccessManagement_Services.cls
public class DGTL_AccessManagement_Services {
    
    public static void clearLastRunTime (List<DGTL_Access_Management__c> list_AccessMgmtNew, Map<Id,DGTL_Access_Management__c> map_AccessMgmtOld){
        Id recordTypeId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Notification').getRecordTypeId();
        list<DGTL_Access_Management__c> list_AccessMgmtToUpdate = new list<DGTL_Access_Management__c>();
        
        for(DGTL_Access_Management__c accessMgmt : list_AccessMgmtNew)
        {   
            if(accessMgmt.RecordTypeId == recordTypeId && 
               accessMgmt.Schedule_Interval_Time__c != map_AccessMgmtOld.get(accessMgmt.Id).get('Schedule_Interval_Time__c')){
                   accessMgmt.Last_Schedule_time__c = null;
            }
        }
    }
}