Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Placement_Layout__r.Date_Formula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Placement_Content__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_KOD__c.object
<CustomObject>
    <label>Placement&amp;KOD</label>
    <nameField>
        <displayFormat>L&amp;K{00000}</displayFormat>
        <label>Layout&amp;KOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements&amp;KODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipName>Layouts_KODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Layouts_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Placements_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compared_Placement_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compared Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Floorset_Plan__r.Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_No__c</fullName>
        <formula>Floorset_Plan__r.Time_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Library</relationshipLabel>
        <relationshipName>Placement_Library</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Types</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Placement Type old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANNER</fullName>
                </value>
                <value>
                    <fullName>CUE</fullName>
                </value>
                <value>
                    <fullName>FEATURE</fullName>
                </value>
                <value>
                    <fullName>OFFER BANNER</fullName>
                </value>
                <value>
                    <fullName>BANNER 1</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 1</label>
                </value>
                <value>
                    <fullName>BANNER 2</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 2</label>
                </value>
                <value>
                    <fullName>BANNER 3</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 3</label>
                </value>
                <value>
                    <fullName>CUE 1</fullName>
                    <isActive>false</isActive>
                    <label>CUE 1</label>
                </value>
                <value>
                    <fullName>CUE 2</fullName>
                    <isActive>false</isActive>
                    <label>CUE 2</label>
                </value>
                <value>
                    <fullName>CUE 3</fullName>
                    <isActive>false</isActive>
                    <label>CUE 3</label>
                </value>
                <value>
                    <fullName>CUE 4</fullName>
                    <isActive>false</isActive>
                    <label>CUE 4</label>
                </value>
                <value>
                    <fullName>CUE 5</fullName>
                    <isActive>false</isActive>
                    <label>CUE 5</label>
                </value>
                <value>
                    <fullName>SUB CUE</fullName>
                    <isActive>false</isActive>
                    <label>SUB CUE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGT_cascadeContentCtr.cls
public class DGT_cascadeContentCtr 
{
    @AuraEnabled
    public static mainReturnDataWpr fetchContents(String recId)
    {
        mainReturnDataWpr rWpr = new mainReturnDataWpr();
        Placement_Content__c pCon = [SELECT Id,Placement_Layout__c,Placement_Library__c,Placement_Layout__r.Device_Type__c,
                                     Placement_Layout__r.Brands__c,Placement_Layout__r.Time_No__c,Placement_Layout__r.Date_Formula__c,Type__c,
                                     Placement_Layout__r.Page_Types__c,(select id,Name,KOD__c,KOD__r.Name from Layouts_KODs__r) FROM Placement_Content__c WHERE Id =: recId];
        
        Id RecordTypeId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        DGTL_Access_Management__c pContentAccMgt = DGTL_DataAccessor.getAccessMang(pCon.Placement_Layout__r.Brands__c, pCon.Placement_Layout__r.Page_Types__c, 'Placement_Content__c', 'DGTL Main',RecordTypeId);
        DGTL_Access_Management__c pContentDetAccMgt = DGTL_DataAccessor.getAccessMang(pCon.Placement_Layout__r.Brands__c, pCon.Placement_Layout__r.Page_Types__c, 'Placement_Content_Detail__c', 'Layout - Content Details',RecordTypeId); 
        system.debug('pContentAccMgt..'+pContentAccMgt);
        system.debug('pContentDetAccMgt..'+pContentDetAccMgt);
        
        if((pContentAccMgt != null ) && (pContentDetAccMgt != null && String.isNotBlank(pContentDetAccMgt.Writable_Fields__c)))
        {
            Map<String, Schema.SObjectField> map_PlConfields = Schema.getGlobalDescribe().get('Placement_Content__c').getDescribe().fields.getMap();
            Map<String, Schema.SObjectField> map_PlConDetfields = Schema.getGlobalDescribe().get('Placement_Content_Detail__c').getDescribe().fields.getMap();
            Set<String> list_AllContentFields = new Set<String>();  list<String> list_ContentReadFields = new list<String>();
            list<String> list_ContentWriteFields = new list<String>();
            if(String.isNotBlank(pContentAccMgt.Writable_Fields__c)) list_AllContentFields.addAll(pContentAccMgt.Writable_Fields__c.split(';')); 
            if(String.isNotBlank(pContentAccMgt.Read_Only_Fields__c)) list_AllContentFields.addAll(pContentAccMgt.Read_Only_Fields__c.split(';'));
           
            if(String.isNotBlank(pContentAccMgt.Read_Only_Fields__c)) list_ContentReadFields.addAll(pContentAccMgt.Read_Only_Fields__c.split(';'));
            if(String.isNotBlank(pContentAccMgt.Writable_Fields__c)) list_ContentWriteFields.addAll(pContentAccMgt.Writable_Fields__c.split(';')); 

            
            
           // String fieldsToDisplay = String.isNotBlank(pContentAccMgt.Writable_Fields__c) ? pContentAccMgt.Writable_Fields__c : 
           // String.isNotBlank(pContentAccMgt.Read_Only_Fields__c) ? pContentAccMgt.Read_Only_Fields__c : null;
            
            String mainConquery = 'SELECT Id,Name,';
            //mainConquery += fieldsToDisplay != null ? (','+ String.join(fieldsToDisplay.split(';'), ',')) : '';
            //----- Querying Read and  write fields
            if(list_AllContentFields.size() > 0){
                for( String field : list_AllContentFields){
                    mainConquery += field+',';
                } 
            }
            // Get kods 
            if(String.isNotBlank(pContentAccMgt.Button__c) && pContentAccMgt.Button__c.contains('Add KOD')){
                system.debug('----kod if condition');
                mainConquery += '(select id,Name,KOD__c,KOD__r.Name from Layouts_KODs__r),';
            }
            mainConquery   += '(SELECT Id,'+String.join(pContentDetAccMgt.Writable_Fields__c.split(';'), ',')+' FROM Placement_Content_Details__r) FROM Placement_Content__c WHERE Id =: recId';
            contentWpr mainCon = new contentWpr();system.debug(mainConquery);
            Placement_Content__c main_pCon = Database.query(mainConquery);
            mainCon.plContent = main_pCon;
            for(Placement_KOD__c kod : main_pCon.Layouts_KODs__r){
                rWpr.linkedKods += kod.KOD__r.Name + ', ';
            }
            rWpr.linkedKods = rWpr.linkedKods.removeEnd(', ');
            Map<String,List<String>> map_PlcDetFieldValus = new Map<String,List<String>>();
            //if(fieldsToDisplay != null ){
               // for(String mpcField : fieldsToDisplay.split(';'))
            if(list_AllContentFields.size() != null ){
                for(String mpcField : list_AllContentFields)
                {
                    if(map_PlConfields.get(mpcField) != Null)
                    {
                        fieldDataWpr mpcData = new fieldDataWpr();
                        mpcData.fieldApi = mpcField;
                        mpcData.fieldLabel = map_PlConfields.get(mpcField).getDescribe().getLabel();
                        mpcData.fieldType = getFieldType(mpcField,map_PlConfields);
                        if(mpcData.fieldType == 'boolean')
                        {
                            mpcData.actualBooleanVal = Boolean.valueof(main_pCon.get(mpcField.trim()));
                            mpcData.newBooleanVal = Boolean.valueof(main_pCon.get(mpcField.trim()));
                        }
                        
                        mpcData.actualFieldValue = String.valueof(main_pCon.get(mpcField.trim()));
                        mpcData.newFieldValue = String.valueof(main_pCon.get(mpcField.trim()));
                        if(list_ContentReadFields.contains(mpcField) && !list_ContentWriteFields.contains(mpcField)){
                            mpcData.isReadOnly = true;
                        }
                        mainCon.list_PlContentFieldData.add(mpcData);
                    }
                }
            }
            if(!main_pCon.Placement_Content_Details__r.isEmpty())
            {
                for(Placement_Content_Detail__c mpcd : main_pCon.Placement_Content_Details__r)
                {
                    contentDetWpr mpcdWpr = new contentDetWpr();
                    mpcdWpr.plContentDetail = mpcd;
                    
                    for(String mpcdField : pContentDetAccMgt.Writable_Fields__c.split(';'))
                    {
                        if(map_PlConDetfields.get(mpcdField) != Null)
                        {
                            fieldDataWpr mpcdData = new fieldDataWpr();
                            mpcdData.fieldApi = mpcdField;
                            mpcdData.fieldLabel = map_PlConDetfields.get(mpcdField).getDescribe().getLabel();
                            mpcdData.fieldType = getFieldType(mpcdField,map_PlConDetfields);
                            if(mpcdData.fieldType == 'boolean')
                            {
                                mpcdData.actualBooleanVal = Boolean.valueof(mpcd.get(mpcdField.trim()));
                                mpcdData.newBooleanVal = Boolean.valueof(mpcd.get(mpcdField.trim()));
                            }
                            
                            mpcdData.actualFieldValue = String.valueof(mpcd.get(mpcdField.trim()));
                            mpcdData.newFieldValue = String.valueof(mpcd.get(mpcdField.trim()));
                            if(map_PlcDetFieldValus.get(mpcdField) == Null) map_PlcDetFieldValus.put(mpcdField,new List<String>());
                            map_PlcDetFieldValus.get(mpcdField).add('Promote: '+(!String.isBlank(String.valueof(mpcd.get(mpcdField.trim()))) ? String.valueof(mpcd.get(mpcdField.trim())) : ''));
                            mpcdData.lis_ChooseOptions = map_PlcDetFieldValus.get(mpcdField);
                            mpcdWpr.list_PlcConDetFieldData.add(mpcdData);
                        }
                    }
                    mainCon.list_contentDetWpr.add(mpcdWpr);
                }
            }
            rWpr.isContentReadOnly = String.isBlank(pContentAccMgt.Writable_Fields__c) && String.isNotBlank(pContentAccMgt.Read_Only_Fields__c) ? true : false;
            rWpr.mainPlcContent = mainCon;
            rWpr.map_PlcDetFieldValusMain = map_PlcDetFieldValus;
            String pLibraryId = pCon.Placement_Library__c;
            Date dateVal = pCon.Placement_Layout__r.Date_Formula__c;
            Decimal timeVal = pCon.Placement_Layout__r.Time_No__c;
            String deviceType = pCon.Placement_Layout__r.Device_Type__c;
            String query = 'SELECT Id,Name,Brand__c,Editorial_Name__c,' ;
            if(list_AllContentFields.size() > 0){
                for( String field : list_AllContentFields){
                    if(!field.equalsIgnoreCase('Brand__c') && !field.equalsIgnoreCase('Editorial_Name__c')) query += field+',';
                } 
            }
            
            String detailFields = String.join(pContentDetAccMgt.Writable_Fields__c.split(';'), ',');
            detailFields += !detailFields.contains('Brand__c') ? ',Brand__c' : '';
            String contentType = pCon.Type__c;
            //query += fieldsToDisplay != null ? ','+ String.join(fieldsToDisplay.split(';'), ',') : '';
            query += '(SELECT Id,'+detailFields+' FROM Placement_Content_Details__r),(select id,Name,KOD__c,KOD__r.Name from Layouts_KODs__r) FROM Placement_Content__c WHERE Placement_Library__c =: pLibraryId AND Id !=: recId AND Placement_Layout__r.Type__c=\'Layout\' AND Active__c = true AND (Type__c =:contentType)';
            query +=' AND ( Placement_Layout__r.Date_Formula__c >:dateVal OR (Placement_Layout__r.Date_Formula__c =:dateVal AND Placement_Layout__r.Time_No__c >: timeVal) OR (Placement_Layout__r.Date_Formula__c =:dateVal AND Placement_Layout__r.Time_No__c >=: timeVal)) Order By Placement_Layout__r.Date_Formula__c '; //AND Placement_Layout__r.Device_Type__c !=:deviceType
            system.debug('query...'+query);
            for(Placement_Content__c pc : Database.query(query))
            {   
                contentWpr rltdCon = new contentWpr();
                rltdCon.plContent = pc;
                for(Placement_KOD__c kod : pc.Layouts_KODs__r){
                     rltdCon.linkedKods += kod.KOD__r.Name + ', ';
                     rltdCon.oldlinkedKods += kod.KOD__r.Name + ', ';
                   }
                 if(rltdCon.linkedKods.contains(', '))
                 rltdCon.linkedKods = rltdCon.linkedKods.removeEnd(', ');
                 if(rltdCon.oldlinkedKods.contains(', '))
                 rltdCon.oldlinkedKods = rltdCon.oldlinkedKods.removeEnd(', ');
                //if(fieldsToDisplay != null ){
                // for(String pcField : fieldsToDisplay.split(';'))
                if(list_AllContentFields.size() != null ){
                    for(String pcField : list_AllContentFields)
                    {
                        if(map_PlConfields.get(pcField) != Null)
                        {
                            fieldDataWpr pcData = new fieldDataWpr();
                            pcData.fieldApi = pcField;
                            pcData.fieldLabel = map_PlConfields.get(pcField).getDescribe().getLabel();
                            pcData.fieldType = getFieldType(pcField,map_PlConfields);
                            if(pcData.fieldType == 'boolean')
                            {
                                pcData.actualBooleanVal = Boolean.valueof(pc.get(pcField.trim()));
                                pcData.newBooleanVal = Boolean.valueof(pc.get(pcField.trim()));
                            }
                            
                            pcData.actualFieldValue = String.valueof(pc.get(pcField.trim()));
                            pcData.newFieldValue = String.valueof(pc.get(pcField.trim()));
                            pcData.lis_ChooseOptions.add('Actual: '+(!String.isBlank(String.valueof(pc.get(pcField.trim()))) ? String.valueof(pc.get(pcField.trim())) : ''));
                            pcData.lis_ChooseOptions.add('Promote: '+(!String.isBlank(String.valueof(main_pCon.get(pcField.trim()))) ? String.valueof(main_pCon.get(pcField.trim())) : ''));
                            rltdCon.list_PlContentFieldData.add(pcData);
                        }
                    }
                }
                if(!pc.Placement_Content_Details__r.isEmpty())
                {
                    for(Placement_Content_Detail__c pcd : pc.Placement_Content_Details__r)
                    {
                        contentDetWpr pcdWpr = new contentDetWpr();
                        pcdWpr.plContentDetail = pcd;
                        
                        for(String pcdField : pContentDetAccMgt.Writable_Fields__c.split(';'))
                        {
                            if(map_PlConDetfields.get(pcdField) != Null)
                            {
                                fieldDataWpr pcdData = new fieldDataWpr();
                                pcdData.fieldApi = pcdField;
                                pcdData.fieldLabel = map_PlConDetfields.get(pcdField).getDescribe().getLabel();
                                pcdData.fieldType = getFieldType(pcdField,map_PlConDetfields);
                                if(pcdData.fieldType == 'boolean')
                                {
                                    pcdData.actualBooleanVal = Boolean.valueof(pcd.get(pcdField.trim()));
                                    pcdData.newBooleanVal = Boolean.valueof(pcd.get(pcdField.trim()));
                                }
                                
                                pcdData.actualFieldValue = String.valueof(pcd.get(pcdField.trim()));
                                pcdData.newFieldValue = String.valueof(pcd.get(pcdField.trim()));
                                pcdData.lis_ChooseOptions.add('Actual: '+(!String.isBlank(String.valueof(pcd.get(pcdField.trim()))) ? String.valueof(pcd.get(pcdField.trim())) : ''));
                                if(map_PlcDetFieldValus.get(pcdField) != Null) pcdData.lis_ChooseOptions.addAll(map_PlcDetFieldValus.get(pcdField)	);
                                pcdWpr.list_PlcConDetFieldData.add(pcdData);
                            }
                        }
                        rltdCon.list_contentDetWpr.add(pcdWpr);
                    }
                }
                rWpr.list_PlcContents.add(rltdCon);
            }
            rWpr.status = 'success';
            rWpr.message = '';
        }
        else
        {
            rWpr.status = 'error';
            rWpr.message = 'No Access records found for you/the current Content Brand..!!';
        }
        return rWpr;
    }
    @AuraEnabled
    public static contentDetWpr addNewPlConDet(String plcId,contentDetWpr selectedPlcDet)
    {
        contentDetWpr pcdWpr = new contentDetWpr();
        pcdWpr.plContentDetail = new Placement_Content_Detail__c();
        pcdWpr.plContentDetail.Placement_Content__c = plcId;
        for(fieldDataWpr f : selectedPlcDet.list_PlcConDetFieldData)
        {
            if(f.fieldType == 'boolean')
            pcdWpr.plContentDetail.put(f.fieldApi,Boolean.valueOf(f.newFieldValue));             
            else
            pcdWpr.plContentDetail.put(f.fieldApi,f.newFieldValue);
            
        }
        pcdWpr.list_PlcConDetFieldData = selectedPlcDet.list_PlcConDetFieldData;
        System.debug('@@==>> pcdWpr: '+pcdWpr.list_PlcConDetFieldData);
        return pcdWpr;
    }
    
    @AuraEnabled
    public static List<contentDetWpr> promotePlConDets(String plcId,List<contentDetWpr> list_AllMainPlcCOnDet)
    {
        List<contentDetWpr> list_contentDetWpr = new List<contentDetWpr>();
        for(contentDetWpr cWpr : list_AllMainPlcCOnDet)
        {
            contentDetWpr pcdWpr = new contentDetWpr();
            pcdWpr.plContentDetail = cWpr.plContentDetail.clone();
            pcdWpr.plContentDetail.Placement_Content__c = (String.isNotBlank(plcId)) ? plcId : null;
            pcdWpr.list_PlcConDetFieldData = cWpr.list_PlcConDetFieldData;
            list_contentDetWpr.add(pcdWpr);
        }
        
        System.debug('@@==>> pcdWpr: '+list_contentDetWpr);
        return list_contentDetWpr;
    }
    
   /* @AuraEnabled
    public static String saveContents(List<Placement_Content__c> list_NewPlcContents,List<Placement_Content_Detail__c> list_NewPlcConDets, List<String> detailIds,boolean linkKODs,list<string> selContKod,string contId)
    {
        system.debug('@@@==>> Detail: '+list_NewPlcConDets);
        system.debug('@@@==>> contents: '+JSON.serialize(list_NewPlcContents));
        try{
            List<sObject> contentsByPermissionList;
            List<sObject> contentDetailsByPermissionList;
            Map<String,List<sObject>> objListMap = new Map<String,List<sObject>>();
            
            if(list_NewPlcContents.size() > 0){objListMap.put('Placement_Content__c',list_NewPlcContents);}
            
            if(list_NewPlcConDets.size() > 0){ objListMap.put('Placement_Content_Detail__c',list_NewPlcConDets); }
            
            if(objListMap.size() > 0){
                Map<String,List<sObject>> convertedObjListMap = DGTL_Util.getConvertedData(objListMap);
                
                if(convertedObjListMap.containsKey('Placement_Content__c')){
                    contentsByPermissionList = (List<SObject>)Type.forName('List<Placement_Content__c>').newInstance();
                    contentsByPermissionList.addAll(convertedObjListMap.get('Placement_Content__c'));
                    upsert contentsByPermissionList;
                }
                
                if(convertedObjListMap.containsKey('Placement_Content_Detail__c')){
                    contentDetailsByPermissionList = (List<SObject>)Type.forName('List<Placement_Content_Detail__c>').newInstance();
                    contentDetailsByPermissionList.addAll(convertedObjListMap.get('Placement_Content_Detail__c'));
                    upsert contentDetailsByPermissionList;
                }
                // Adding linked kods
                if(linkKODs){
                    list<Placement_KOD__c> list_KodInsert = new list<Placement_KOD__c>();
                    list<Placement_KOD__c> list_KodDelete = new list<Placement_KOD__c>();
                    for(Placement_KOD__c kod : [select Id,KOD__c,Placement_Content__c,Placement_Library__c from Placement_KOD__c where Placement_Content__c IN : selContKod])
                    {
                        list_KodDelete.add(kod);
                    }
                    if(!list_KodDelete.isEmpty()){
                        delete list_KodDelete;
                    }

                    for(Placement_KOD__c kod : [select Id,KOD__c,Placement_Content__c,Placement_Library__c from Placement_KOD__c where Placement_Content__c=:contId])
                    {
                        for(string conId : selContKod){
                            Placement_KOD__c clonkod = new Placement_KOD__c();
                            clonkod = kod.clone(false, false, false, false);
                            clonkod.Placement_Content__c = conId;
                            list_KodInsert.add(clonkod);
                        }
                    }
                    if(!list_KodInsert.isEmpty()){
                        insert list_KodInsert;
                    }
                }
            }
            
            List<Placement_Content_Detail__c> deletedList = new List<Placement_Content_Detail__c>();
            system.debug('detailIds------'+detailIds);
            if(detailIds.size() > 0){
                deletedList = [Select id, Name from Placement_Content_Detail__c where id in :detailIds ];
                system.debug('deletedList ---'+deletedList);
                delete deletedList;
            } 
            return 'Success';
        }
        catch(exception e){
            return 'Error: '+String.valueOf(e)+'. At: '+e.getStackTraceString();
        }
    }*/
    
    @AuraEnabled
    public static String saveContents(List<Placement_Content__c> list_NewPlcContents,List<Placement_Content_Detail__c> list_NewPlcConDets, List<String> detailIds,boolean linkKODs,list<string> selContKod,string contId)
    {
        system.debug('@@@==>> Detail: '+list_NewPlcConDets);
        try{
            Upsert list_NewPlcContents;    
            Upsert list_NewPlcConDets;
            
            List<Placement_Content_Detail__c> deletedList = new List<Placement_Content_Detail__c>();
            system.debug('detailIds------'+detailIds);
            
                // Adding linked kods
                if(linkKODs){
                    list<Placement_KOD__c> list_KodInsert = new list<Placement_KOD__c>();
                    list<Placement_KOD__c> list_KodDelete = new list<Placement_KOD__c>();
                    for(Placement_KOD__c kod : [select Id,KOD__c,Placement_Content__c,Placement_Library__c from Placement_KOD__c where Placement_Content__c IN : selContKod])
                    {
                        list_KodDelete.add(kod);
                    }
                    if(!list_KodDelete.isEmpty()){
                        delete list_KodDelete;
                    }

                    for(Placement_KOD__c kod : [select Id,KOD__c,Placement_Content__c,Placement_Library__c from Placement_KOD__c where Placement_Content__c=:contId])
                    {
                        for(string conId : selContKod){
                            Placement_KOD__c clonkod = new Placement_KOD__c();
                            clonkod = kod.clone(false, false, false, false);
                            clonkod.Placement_Content__c = conId;
                            list_KodInsert.add(clonkod);
                        }
                    }
                    if(!list_KodInsert.isEmpty()){
                        insert list_KodInsert;
                    }
                }
            
            if(detailIds.size() > 0){
                deletedList = [Select id, Name from Placement_Content_Detail__c where id in :detailIds ];
                system.debug('deletedList ---'+deletedList);
                delete deletedList;
            } 
            return 'Success';
        }
        catch(exception e){
            return 'Error: '+String.valueOf(e)+'. At: '+e.getStackTraceString();
        }
    }
    
    public static List<fieldDataWpr> mapAllFields()
    {
        List<fieldDataWpr> list_fieldDataWpr = new List<fieldDataWpr>();
        return list_fieldDataWpr;
    }
    public static String getFieldType(String fieldApiName,Map<String,Schema.SObjectField> map_FieldSchema)
    {
        if(map_FieldSchema.get(fieldApiName).getDescribe().getType() == Schema.DisplayType.BOOLEAN)
        {
            return 'boolean';                    
        }
        else if(map_FieldSchema.get(fieldApiName).getDescribe().getType() == Schema.DisplayType.TEXTAREA && 
                map_FieldSchema.get(fieldApiName).getDescribe().isHtmlFormatted())
        {
            return 'richtext'; 
        }
        else
        {
            return 'text'; 
        }
    } 
    
    public class mainReturnDataWpr
    {
        @AuraEnabled public contentWpr mainPlcContent{get;set;}
        @AuraEnabled public List<contentWpr> list_PlcContents{get;set;}
        @AuraEnabled public Map<String,List<String>> map_PlcDetFieldValusMain{get;set;}
        @AuraEnabled public String status{get;set;}
        @AuraEnabled public String message{get;set;}
        @AuraEnabled public Boolean isContentReadOnly{get;set;}
        @AuraEnabled public String linkedKods{get;set;}
        public mainReturnDataWpr()
        {
            mainPlcContent = new contentWpr();
            list_PlcContents = new List<contentWpr>();
            map_PlcDetFieldValusMain = new Map<String,List<String>>();
            status = '';
            message = '';
            isContentReadOnly = false;
            linkedKods = '';
        }
    }
    
    public class contentWpr
    {
        @AuraEnabled public Placement_Content__c plContent{get;set;}
        @AuraEnabled public List<contentDetWpr> list_contentDetWpr{get;set;}
        @AuraEnabled public List<fieldDataWpr> list_PlContentFieldData{get;set;}
        @AuraEnabled public Boolean isContentSelected{get;set;}
        @AuraEnabled public String linkedKods{get;set;}
        @AuraEnabled public String oldlinkedKods{get;set;}
        public contentWpr()
        {
            plContent = new Placement_Content__c();
            list_contentDetWpr = new List<contentDetWpr>();
            list_PlContentFieldData = new List<fieldDataWpr>();
            isContentSelected = false;
            linkedKods = '';
            oldlinkedKods = '';
        }
    }
    public class contentDetWpr
    {
        @AuraEnabled public Placement_Content_Detail__c plContentDetail{get;set;}
        @AuraEnabled public Boolean isNew{get;set;}
        @AuraEnabled public List<fieldDataWpr> list_PlcConDetFieldData{get;set;}
        @AuraEnabled public Boolean isConDetSelected{get;set;}
        public contentDetWpr()
        {
            plContentDetail = new Placement_Content_Detail__c();
            isNew = false;
            list_PlcConDetFieldData = new List<fieldDataWpr>();
            isConDetSelected = false;
        }
    }
    public class fieldDataWpr
    {
        @AuraEnabled public Boolean isChecked{get;set;}
        @AuraEnabled public String fieldLabel{get;set;}
        @AuraEnabled public String fieldApi{get;set;}
        @AuraEnabled public String actualFieldValue{get;set;}
        @AuraEnabled public String newFieldValue{get;set;}
        @AuraEnabled public String fieldType{get;set;}
        @AuraEnabled public Boolean actualBooleanVal{get;set;}
        @AuraEnabled public Boolean newBooleanVal{get;set;}
        @AuraEnabled public List<String> lis_ChooseOptions{get;set;}
        @AuraEnabled public Boolean isReadOnly{get;set;}
        public fieldDataWpr()
        {
            fieldLabel = '';
            fieldApi = '';
            actualFieldValue = '';
            newFieldValue = '';
            fieldType = '';
            actualBooleanVal = false;
            newBooleanVal = false;
            lis_ChooseOptions = new List<String>();
            isChecked = false;
        }
    }
}