Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Minute__c</fullName>
        <label>Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_type__c</fullName>
        <inlineHelpText>Select the type of placement from the drop down. E.g. Banner, Cue, feature, Site Majority Offer etc.</inlineHelpText>
        <label>Placement type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Cue</fullName>
                </value>
                <value>
                    <fullName>Site Majority Offer</fullName>
                </value>
                <value>
                    <fullName>Floating Cue/Collection Cue</fullName>
                </value>
                <value>
                    <fullName>Collection Header</fullName>
                </value>
                <value>
                    <fullName>Stack Header</fullName>
                </value>
                <value>
                    <fullName>Product Page Header</fullName>
                </value>
                <value>
                    <fullName>Offer Copy</fullName>
                </value>
                <value>
                    <fullName>OLCO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Floorset Plan</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Brands__c</field>
                <operation>equals</operation>
                <valueField>DGTL_Floorset_Plan__c.Brands__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Minute__c</fullName>
        <label>End Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Minute__c</fullName>
        <label>Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_CloneLayoutContentTest.cls
/************************************************************
Name          : DGTL_CloneLayoutContentTest
Description   : Test Class for DGTL_CloneLayoutContent      
*************************************************************/
@isTest
public class DGTL_CloneLayoutContentTest {
 @TestSetup
        static void datasetup(){
            Test.startTest();
             list<DGTL_Floorset_Plan__c> list_Floorset = new list<DGTL_Floorset_Plan__c>();
            list_Floorset.add(DGTL_TestDataFactory.createFloorsetPlan('VS',date.today(),'5 AM','Update'));
            list_Floorset.add(DGTL_TestDataFactory.createFloorsetPlan('VS',date.today()+4,'5 AM','Update'));
            list_Floorset[0].Minute__c = null;
            list_Floorset[1].Minute__c = '10';
            insert  list_Floorset;
            update  list_Floorset;
            list<Placement_Library__c> list_library = new list<Placement_Library__c>();
            list_library.add(DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1, 'VS', 'Home Page', '5 AM', '5 AM', 'Desktop', 'Approved', 'Non Offer', 'mainMsg'));
            list_library.add(DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+2, 'VS', 'Home Page', '5 AM', '9 AM', 'Desktop', 'Approved', 'Non Offer', 'mainMsg2')); 
            list_library.add(DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1, 'VS', 'Editorials', '5 AM', '5 AM', 'Desktop', 'Approved', 'Non Offer', 'mainMsg3'));
            list_library[0].Start_Minute__c = null;
            list_library[0].End_Minute__c = null;
            list_library[0].Placement_type__c = 'cue';
            list_library[0].Collection_Page_Url__c = 'collection page url test';
            list_library[2].Editorial_Name__c = 'Edt name Clone';
            list_library[2].Placement_type__c = 'cue';
            insert list_library;
            insert DGTL_TestDataFactory.createPlacementContentDetail(null,string.valueOf(list_library[0].Id),false,'Slide 1','assetPath','copy');
            Placement_Library__c clonelib = list_library[0].clone();
            insert clonelib;
            list<Placement_Layout__c> list_layout = new list<Placement_Layout__c>();
            list_layout.add(DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',list_Floorset[1].Id, 'Layout'));
            list_layout.add(DGTL_TestDataFactory.createPlacementLayout('VS','Sport LP','Desktop',list_Floorset[1].Id, 'Layout'));
            list_layout.add(DGTL_TestDataFactory.createPlacementLayout('VS','Editorials','Desktop',list_Floorset[1].Id, 'Layout'));
            list_layout[2].Collection_Page_Name__c = 'Editorial Page test';
            insert list_layout;
            List<Placement_Content__c> list_Contents = DGTL_TestDataFactory.createPlacementContentlist(list_layout[0].Id,list_layout[0].Page_Types__c, 1,null,'Some Message','Video','Controlled','Feature','Non Offer');      
            list_Contents[0].Content_Type__c = 'Carousel';
            insert list_Contents;
            Test.stopTest();
        }
    static testmethod void CloneContentsTest(){
        Test.startTest();
        list<DGTL_Floorset_Plan__c> list_floorset = [select id from DGTL_Floorset_Plan__c];
        list<string> list_floorsetIds = new list<string>();
        Placement_Layout__c lay = new Placement_Layout__c(Brands__c = 'VS',Page_Types__c = 'Home Page',Device_Type__c = 'Desktop',Floorset_Plan__c =list_floorset[0].Id);
        Placement_Layout__c lay2 = new Placement_Layout__c(Brands__c = 'VS',Page_Types__c = 'Editorials',Device_Type__c = 'Desktop',Floorset_Plan__c =list_floorset[1].Id);
        list<Placement_Layout__c> list_layout = new list<Placement_Layout__c>();
        list_layout.add(lay);
        list_layout.add(lay2);
        
        List<String> PageTypes = new List<String> ();
        PageTypes.add('Home Page');PageTypes.add('Editorials');
        List<String> deviceTypes = new List<String> ();
        deviceTypes.add('Desktop'); deviceTypes.add('Mobile');
        
        DGTL_CloneLayoutContent.fetchFloorsetWrapper(lay,date.today()-10,date.today()+10,PageTypes,deviceTypes);
        DGTL_CloneLayoutContent.fetchFloorsetWrapper(lay2,date.today()-10,date.today()+10,PageTypes,deviceTypes);
        for(DGTL_Floorset_Plan__c flr : list_floorset){
            list_floorsetIds.add(string.valueof(flr.Id));
        }
        list<Placement_Content__c> lst_Con = Database.query(DGTL_DataAccessor.getSobjectSoql(new Placement_Content__c()));
        Placement_Content_Detail__c contdet = new Placement_Content_Detail__c();
        contdet.Placement_Content__c = lst_Con[0].Id;
        insert contdet;
        DGTL_CloneLayoutContent.cloneContentsToLayout(lst_Con,lay2,list_layout);
        DGTL_CloneLayoutContent.cloneContentsToLayout(lst_Con,lay,list_layout);
        DGTL_CloneLayoutContent.getDependentMap(lay,'Brands__c','Page_Types__c');
        Test.stopTest();
        }
}