Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_Schedule_time__c</fullName>
        <label>Last Schedule time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Interval_Time__c</fullName>
        <label>Schedule Interval Time(For Notification)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 mins</fullName>
                </value>
                <value>
                    <fullName>60 mins</fullName>
                </value>
                <value>
                    <fullName>2 hrs</fullName>
                </value>
                <value>
                    <fullName>3 hrs</fullName>
                </value>
                <value>
                    <fullName>4 hrs</fullName>
                </value>
                <value>
                    <fullName>5 hrs</fullName>
                </value>
                <value>
                    <fullName>6 hrs</fullName>
                </value>
                <value>
                    <fullName>7 hrs</fullName>
                </value>
                <value>
                    <fullName>8 hrs</fullName>
                </value>
                <value>
                    <fullName>9 hrs</fullName>
                </value>
                <value>
                    <fullName>10 hrs</fullName>
                </value>
                <value>
                    <fullName>11 hrs</fullName>
                </value>
                <value>
                    <fullName>12 hrs</fullName>
                </value>
                <value>
                    <fullName>13 hrs</fullName>
                </value>
                <value>
                    <fullName>14 hrs</fullName>
                </value>
                <value>
                    <fullName>24 hrs</fullName>
                </value>
                <value>
                    <fullName>1.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>1.5 hrs</label>
                </value>
                <value>
                    <fullName>10.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>10.5 hrs</label>
                </value>
                <value>
                    <fullName>11.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>11.5 hrs</label>
                </value>
                <value>
                    <fullName>12.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>12.5 hrs</label>
                </value>
                <value>
                    <fullName>13.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>13.5 hrs</label>
                </value>
                <value>
                    <fullName>2.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>2.5 hrs</label>
                </value>
                <value>
                    <fullName>3.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>3.5 hrs</label>
                </value>
                <value>
                    <fullName>4.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>4.5 hrs</label>
                </value>
                <value>
                    <fullName>45 mins</fullName>
                    <isActive>false</isActive>
                    <label>45 mins</label>
                </value>
                <value>
                    <fullName>5.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>5.5 hrs</label>
                </value>
                <value>
                    <fullName>6.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>6.5 hrs</label>
                </value>
                <value>
                    <fullName>7.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>7.5 hrs</label>
                </value>
                <value>
                    <fullName>8.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>8.5 hrs</label>
                </value>
                <value>
                    <fullName>9.5 hrs</fullName>
                    <isActive>false</isActive>
                    <label>9.5 hrs</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Notification</fullName>
        <active>true</active>
        <label>Notification</label>
    </recordTypes>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset_Path__c</fullName>
        <inlineHelpText>Enter creative delivery shared drive path</inlineHelpText>
        <label>Asset Path</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Copy__c</fullName>
        <inlineHelpText>Enter copy for offer/non-offer placements</inlineHelpText>
        <label>Copy</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Slides__c</fullName>
        <inlineHelpText>Select slide number to differentiate the slides in a carousel</inlineHelpText>
        <label>Slides</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slide 1</fullName>
                </value>
                <value>
                    <fullName>Slide 2</fullName>
                </value>
                <value>
                    <fullName>Slide 3</fullName>
                </value>
                <value>
                    <fullName>Slide 4</fullName>
                </value>
                <value>
                    <fullName>Slide 5</fullName>
                </value>
                <value>
                    <fullName>Slide 6</fullName>
                </value>
                <value>
                    <fullName>Slide 7</fullName>
                </value>
                <value>
                    <fullName>Slide 8</fullName>
                </value>
                <value>
                    <fullName>Slide 9</fullName>
                </value>
                <value>
                    <fullName>Slide 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_AccessManagement_HandlerTest.cls
/************************************************************
Name          : DGTL_AccessManagement_HandlerTest
Description   : Test Class for DGTL_AccessManagementTrigger ,DGTL_AccessManagement_Handler,DGTL_AccessManagement_Services
*************************************************************/
@isTest
public class DGTL_AccessManagement_HandlerTest {
    static testmethod void  method1(){
        Id recordTypeId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Notification').getRecordTypeId();
        
        list<DGTL_Access_Management__c> list_AccessMng = new list<DGTL_Access_Management__c>();
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;','','',
                                                                      recordTypeId,'DGTL_Merchandiser'));
        list_AccessMng[0].Schedule_Interval_Time__c = '30 mins';
        list_AccessMng[0].Last_Schedule_time__c = System.now();
        insert list_AccessMng;
        
        list_AccessMng[0].Schedule_Interval_Time__c = '60 mins';
        update list_AccessMng;
        
        delete list_AccessMng;
        
    }
    
}