Digital/objects/DGTL_Task__c.object
<CustomObject>
    <label>Digital Task</label>
    <nameField>
        <displayFormat>TSK-{0000000000}</displayFormat>
        <label>Digital Task No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Digital Task</relationshipLabel>
        <relationshipName>Digital_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Task</label>
        <referenceTo>DGTL_Task__c</referenceTo>
        <relationshipLabel>Digital Task</relationshipLabel>
        <relationshipName>Digital_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipName>Task_Digital</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Inprogress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>User_Task</fullName>
        <active>true</active>
        <label>User Task</label>
    </recordTypes>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Placement_Layout__r.Date_Formula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Content_Self__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content Self</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_KOD__c.object
<CustomObject>
    <label>Placement&amp;KOD</label>
    <nameField>
        <displayFormat>L&amp;K{00000}</displayFormat>
        <label>Layout&amp;KOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements&amp;KODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipName>Layouts_KODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Layouts_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/classes/DGTL_KODTriggerHandler.cls
public class DGTL_KODTriggerHandler {
    
    public void handleKODStatusChange(){
        List<KOD__c> kodList = (List<KOD__c>) trigger.new;
        Map<Id,KOD__c> kodOldMap = (Map<Id,KOD__c>) trigger.oldMap;
        Set<Id> cancelledKODIdSet = new Set<Id>();
        
        for(KOD__c kod : kodList){
            if(kod.Offer_Status__c != kodOldMap.get(kod.Id).Offer_Status__c){
                
                if(kod.Offer_Status__c.equalsIgnoreCase('Cancelled')){
                    cancelledKODIdSet.add(kod.Id);
                }
            }
        }
        
        // START - single kod placement content object logic
       /* if(cancelledKODIdSet.size() > 0){
            Set<Id> contentIds = new Set<Id>();
            List<DGTL_Task__c> taskToUpdate = new List<DGTL_Task__c>();
            List<Placement_Content__c> pcToUpdate = new List<Placement_Content__c>();
            
            for(Placement_Content__c pc : [SELECT Id,Active__c FROM Placement_Content__c WHERE KOD__C IN:cancelledKODIdSet]){
                pc.Active__c = false;
                pcToUpdate.add(pc);
                contentIds.add(pc.Id);
            }
            
            if(pcToUpdate.size() > 0){
                update pcToUpdate;
            }
            
            for(DGTL_Task__c task : [SELECT Id, Status__c FROM DGTL_Task__c WHERE RecordType.DeveloperName='User_Task' AND 
                                     (Placement_Content__c IN :contentIds 
                                      OR Parent_Task__r.Placement_Content__c IN:contentIds)])
            {
                task.Status__c = 'Cancelled';
                taskToUpdate.add(task);
            }
            
            if(taskToUpdate.size() > 0){
                update taskToUpdate;
            }
        } */// END - single kod placement content object logic
        
        
        // junction object logic 
        if(cancelledKODIdSet.size() > 0){
            Set<Id> contentIds = new Set<Id>();
            
            for(Placement_KOD__c pKod : [SELECT Id,KOD__c,Placement_Content__c FROM Placement_KOD__c
                                         WHERE KOD__c IN:cancelledKODIdSet AND Placement_Content__r.Date_Formula__c > TODAY]){
                contentIds.add(pKod.Placement_Content__c);
            }
            
            // logic with content
            if(contentIds.size() > 0){
                List<Placement_Content__c> pcToUpdate = new List<Placement_Content__c>();
                List<DGTL_Task__c> taskToUpdate = new List<DGTL_Task__c>();
                
                for(Placement_Content__c pc : [SELECT Id,Active__c FROM Placement_Content__c WHERE Id IN:contentIds]){
                    pc.Active__c = false;
                    pcToUpdate.add(pc);
                }
                
                if(pcToUpdate.size() > 0){
                    update pcToUpdate;
                }
                
                for(DGTL_Task__c task : [SELECT Id, Status__c FROM DGTL_Task__c WHERE RecordType.DeveloperName='User_Task' AND 
                                         (Placement_Content__c IN :contentIds 
                                         OR Parent_Task__r.Placement_Content__c IN:contentIds)]){
                    task.Status__c = 'Cancelled';
                    taskToUpdate.add(task);
                }
                
                if(taskToUpdate.size() > 0){
                    update taskToUpdate;
                }
                
                // not putting try catch for now...
                DELETE[SELECT Id FROM Placement_KOD__c WHERE Placement_Content__c IN:contentIds];
            }
            
        } 
    }

}