Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/classes/DGTL_WrapperClasses.cls
/*
 * Name 	   : DGTL_WrapperClasses
 * Description : This class contains wrapper classes for digital applicaiton  
 * 
 */
public class DGTL_WrapperClasses {
    
    
    /*
     * Name 	   : LayoutSearchWrp
     * Description : This class contains list of variables, which is returned on digital layout search   
     * 
     */
    public class LayoutSearchResults
    {
        @AuraEnabled public Placement_Layout__c plaLayout{get;set;}
        @AuraEnabled public String pLayoutId{get;set;}
        @AuraEnabled public String pLibraryId{get;set;}
        @AuraEnabled public String selectedFloorset {get;set;}
        @AuraEnabled public List<Placement_Layout__c> list_PlacLytFloorset {get;set;}
        @AuraEnabled public String errorStatus{get;set;}
        @AuraEnabled public String errorCode{get;set;}
        @AuraEnabled public List<contentWprNew> list_contentWpr{get;set;}
        @AuraEnabled public Map<String,String> readFieldsMap {get;set;}
        @AuraEnabled public Map<String,String> editFieldsMap {get;set;}
        @AuraEnabled public Map<String,String> detailReadFieldsMap {get;set;}
        @AuraEnabled public Map<String,String> detailWriteFieldsMap {get;set;}
        @AuraEnabled public Map<String, String> miniViewFieldsMap{get;set;}
        @AuraEnabled public String buttons {get;set;}
        @AuraEnabled public Boolean isEditable {get;set;}
        @AuraEnabled public Boolean hasContents {get;set;}
        @AuraEnabled public date nextDt {get;set;}
        @AuraEnabled public date backDt {get;set;}
        @AuraEnabled public date dateVal {get;set;}
        @AuraEnabled public Decimal timeVal {get;set;}
        @AuraEnabled public String timeValStr {get;set;}
        @AuraEnabled public String unsavedContAlert {get;set;}
        @AuraEnabled public String userDefaultBrand {get;set;}
        @AuraEnabled public Map<String,String> transactionMessageMap {get;set;}
        @AuraEnabled public Boolean layoutHasComments {get;set;}
        @AuraEnabled public Map<string,Integer> ContentTypesBtns{get;set;}
        @AuraEnabled public Boolean isPreviousLayout {get;set;}
        public LayoutSearchResults()
        {
            timeValStr = '';
            unsavedContAlert = '';
            pLayoutId = '';
            pLibraryId = '';
            selectedFloorset = '';
            buttons = '';
            errorCode = '';
            errorStatus = '';
            list_contentWpr = new List<contentWprNew>();
            readFieldsMap = New Map<String,String>();
            editFieldsMap = New Map<String,String>();
            detailReadFieldsMap = new Map<String,String>();
        	detailWriteFieldsMap = new Map<String,String>();
            miniViewFieldsMap = new Map<String,String>();
            transactionMessageMap = new Map<String,String>();
            isEditable = false ; 
            hasContents = false;            
            nextDt = Null;
            backDt = Null;
            timeVal = Null; 
            list_PlacLytFloorset = NEW List<Placement_Layout__c>();
            Placement_Layout__c obj_placelayout = NEW Placement_Layout__c();
            list_PlacLytFloorset.add(obj_placelayout);
            userDefaultBrand = '';
            layoutHasComments = false;
            ContentTypesBtns = new Map<string,Integer>();
            isPreviousLayout = false;
            
        }
    }
    
    public class KODDetail{
        @AuraEnabled public String name{get;set;}
        @AuraEnabled public String id{get;set;}
        
    }
    
    public class contentWprNew
    {
        @AuraEnabled public String conId{get;set;}
        @AuraEnabled public String errorStatus {get;set;}
        @AuraEnabled public Placement_Content__c pContentRec{get;set;}
        @AuraEnabled public List<String> detailAllFeildList {get;set;}
        @AuraEnabled public ContentDetailWrp ContentDetWpr{get;set;}
        @AuraEnabled public  List<KODDetail> kodList{get;set;}
        @AuraEnabled public  Boolean hasNewComments{get;set;}
        @AuraEnabled public  Boolean cascade{get;set;}
        @AuraEnabled public  Boolean removeBtn{get;set;}
        @AuraEnabled public  Boolean commentBtn{get;set;}
        @AuraEnabled public  Boolean historyBtn{get;set;}
        @AuraEnabled public  Boolean updateContent{get;set;}
        @AuraEnabled public  Boolean abTestBtn{get;set;}
        @AuraEnabled public  Boolean TakedownBtns{get;set;}
        @AuraEnabled public  Boolean addKOD{get;set;}
        @AuraEnabled public  Boolean enableContentTypePrompt{get;set;}
        @AuraEnabled public  List<String> ContentTypesList{get;set;}
        @AuraEnabled public  Boolean createTicketBtn{get;set;}
        @AuraEnabled public String clonedContId{get;set;}

        public contentWprNew()
        {
            conId = '';
            clonedContId = '';
            pContentRec = new Placement_Content__c();
            
            detailAllFeildList = new List<String>();
            ContentDetWpr = New ContentDetailWrp();
            kodList = new List<KODDetail>();
            hasNewComments = false;
            cascade = false;
            removeBtn = false;
            commentBtn = false;
            historyBtn = false;
            updateContent = false;
            abTestBtn = false;
            TakedownBtns = false;
            addKOD = false;
            enableContentTypePrompt = false;
            ContentTypesList = new list<string>();
            createTicketBtn = false;
        }
    }
    
        

	 /*
     * Name 	   : ContentDetailWrp
     * Description : This class contains list of variables for storing content Details in Layout Tab
     */    
     public class ContentDetailWrp
    {
        @AuraEnabled public String errorStatus{get;set;}
        @AuraEnabled public Boolean hasContents {get;set;}
        @AuraEnabled public Boolean isCarousel {get;set;}
        @AuraEnabled public list<Placement_Content_Detail__c> detailList {get;set;}
        @AuraEnabled public list<Placement_Content_Detail__c> detailDeleteList {get;set;}
        
        public ContentDetailWrp()
        {
            errorStatus = '';
            hasContents = false;
            isCarousel = false;
            detailList = New list<Placement_Content_Detail__c>();
            detailDeleteList = New list<Placement_Content_Detail__c>();
        }
    }
    
    public class FollowDetails{
        @AuraEnabled public Boolean isFeedEnabled;
        @AuraEnabled public Boolean isFollowed;
        
        public FollowDetails(){
            isFeedEnabled = false;
            isFollowed = false;
        }
    }
    
    public class UserComparePreferences{
        @AuraEnabled public Boolean hasUserPreference;
        @AuraEnabled public DGTL_Access_Management__c accMgt;
        @AuraEnabled public List<String> selectedOptions;
        @AuraEnabled public List<DGTL_ComparePlcLayout_Ctr.SelectOption> options;
        
    }
    

}