Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/DGTL_Task__c.object
<CustomObject>
    <label>Digital Task</label>
    <nameField>
        <displayFormat>TSK-{0000000000}</displayFormat>
        <label>Digital Task No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Digital Task</relationshipLabel>
        <relationshipName>Digital_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipName>Task_Digital</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__r.Name</formula>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Inprogress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>User_Task</fullName>
        <active>true</active>
        <label>User Task</label>
    </recordTypes>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Digital/objects/Placement_KOD__c.object
<CustomObject>
    <label>Placement&amp;KOD</label>
    <nameField>
        <displayFormat>L&amp;K{00000}</displayFormat>
        <label>Layout&amp;KOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements&amp;KODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipName>Layouts_KODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Layouts_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/classes/DGTL_KODTriggerHandlerTest.cls
@isTest
public class DGTL_KODTriggerHandlerTest {
    
    @testSetup
    static void setupData(){
        Id userTaskRecordTypeId = [SELECT Id,DeveloperName FROM RecordType WHERE sObjectType='DGTL_Task__c' AND  DeveloperName='User_Task'].Id;
        
        KOD__c kod = new KOD__c(Name='Test KOD');
        insert kod;
        
        DGTL_Floorset_Plan__c vsFloorsetPlan = DGTL_TestDataFactory.createFloorsetPlan('VS',DATE.today().addDays(1),'2 AM','Update');
        insert vsFloorsetPlan;
        
        Placement_Layout__c layout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',vsFloorsetPlan.Id, 'Layout');
        insert layout;
        
        //create placement contents
       List<Placement_Content__c> pContList = DGTL_TestDataFactory.createPlacementContentlist(null,'', 1,
                                                                                                 null,'','Video',
                                                                                                  'Controlled','Feature','Offer');
        pContList[0].Placement_Layout__c = layout.Id;
        pContList[0].KOD__c = kod.Id;
        insert pContList;
        
        Placement_KOD__c pKod = new Placement_KOD__c(KOD__c=kod.Id, Placement_Content__c=pContList[0].Id);
        insert pKod;
        
        DGTL_Task__c digitalTask = new DGTL_Task__c();
        digitalTask.RecordTypeId = userTaskRecordTypeId;
        digitalTask.Placement_Content__c = pContList[0].Id;
        digitalTask.Status__c = 'New';
        
        insert digitalTask;
        
    }
    
    public static testMethod void handleKODStatusChangeTest(){
        KOD__c kod = [SELECT Id,Offer_Status__c FROM KOD__c LIMIT 1];
        
        Test.startTest();
        kod.Offer_Status__c = 'Cancelled';
        update kod;
        Test.stopTest();
    }

}