Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_PlacementContentViewTest.cls
/************************************************************
Name          : DGTL_PlacementContentViewTest
Description   : Test Class for DGTL_PlacementContentView  
*************************************************************/
@isTest
public class DGTL_PlacementContentViewTest {
    
    
    static testmethod void testMethod1(){
        Test.startTest();
        DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        list<Placement_Content__c> list_Content = DGTL_TestDataFactory.createPlacementContentlist(testLayout.Id,testLayout.Page_Types__c, 1,
                                                                                                  null,'Some Message','Video','Controlled','Feature','Offer');
        insert list_Content;
        DGTL_PlacementContentView.getLayoutId(list_Content[0].Id);
        Test.stopTest();
    }
            

}