Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Buttons__c</fullName>
        <label>Buttons</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>TEXT(Placement_Layout__r.Brands__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Unapproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Unapproved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Page</fullName>
                </value>
                <value>
                    <fullName>Landing Page</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset_Path__c</fullName>
        <inlineHelpText>Enter creative delivery shared drive path</inlineHelpText>
        <label>Asset Path</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Placement_Content__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy__c</fullName>
        <inlineHelpText>Enter copy for offer/non-offer placements</inlineHelpText>
        <label>Copy</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Slides__c</fullName>
        <inlineHelpText>Select slide number to differentiate the slides in a carousel</inlineHelpText>
        <label>Slides</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slide 1</fullName>
                </value>
                <value>
                    <fullName>Slide 2</fullName>
                </value>
                <value>
                    <fullName>Slide 3</fullName>
                </value>
                <value>
                    <fullName>Slide 4</fullName>
                </value>
                <value>
                    <fullName>Slide 5</fullName>
                </value>
                <value>
                    <fullName>Slide 6</fullName>
                </value>
                <value>
                    <fullName>Slide 7</fullName>
                </value>
                <value>
                    <fullName>Slide 8</fullName>
                </value>
                <value>
                    <fullName>Slide 9</fullName>
                </value>
                <value>
                    <fullName>Slide 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGT_cascadeContentCtrTest.cls
/************************************************************
Name          : DGT_cascadeContentCtrTest
Description   : Test Class for DGT_cascadeContentCtr
*************************************************************/
@isTest

public class DGT_cascadeContentCtrTest {
    
    
    @TestSetup
    static void datasetup(){
         DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        DGTL_Floorset_Plan__c testFloorset1 = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '11 AM', 'Update');
        insert testFloorset1;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        Placement_Layout__c testLayout1 = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Mobile',testFloorset.Id, 'Layout');
        insert testLayout1;
        Placement_Layout__c testLayout2 = DGTL_TestDataFactory.createPlacementLayout('VS','Bras LP','Desktop',testFloorset.Id, 'Layout');
        insert testLayout2;
        
        Placement_Library__c testLib = DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1,
                                                                                   'VS', 'Home Page', '5 AM', '5 AM',
                                                                                   'Desktop', 'Approved', 'Non Offer', 'mainMsg');
        insert testLib;
        
        list<Placement_Content__c> list_Content = new  list<Placement_Content__c>();
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout.Id, testLib.Id));
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout1.Id, testLib.Id));
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout2.Id, testLib.Id));
        
        insert list_Content;
        
        list<Placement_Content_Detail__c> list_contentDetail = new List<Placement_Content_Detail__c>();
        Placement_Content_Detail__c contentDetail = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, testLib.Id,
                                                                                                      false, 'Slide 1', 'asset path', 'Copy text');
        
        Placement_Content_Detail__c contentDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[1].Id, testLib.Id,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        Placement_Content_Detail__c contentDetail2 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[2].Id, testLib.Id,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        list_contentDetail.add(contentDetail);
        list_contentDetail.add(contentDetail1);
        list_contentDetail.add(contentDetail2);
        insert list_contentDetail;
        
        Id fieldAccessId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        list<DGTL_Access_Management__c> list_AccessMng = new list<DGTL_Access_Management__c>();
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Has_Unapproved__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Has_Unapproved__c','',
                                                                      'DGTL Main',fieldAccessId,'DGTL_Merchandiser'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Is_Deleted__c','Asset_Path__c;Copy__c;Is_Deleted__c','',
                                                                      'Layout - Content Details',fieldAccessId,'DGTL_Merchandiser'));
        list_AccessMng[0].Buttons__c = 'clone';
        insert list_AccessMng;
        
        
        
        list_contentDetail[0].Slides__c = 'Slide 2'; list_contentDetail[0].Asset_Path__c = 'Slide 2'; list_contentDetail[0].Is_Deleted__c = true;
        list_contentDetail[1].Slides__c = 'Slide 2'; list_contentDetail[1].Asset_Path__c = 'Slide 2'; 
        list_contentDetail[2].Slides__c = 'Slide 2'; list_contentDetail[2].Asset_Path__c = 'Slide 2';
        update list_contentDetail;
    }
    
    static testmethod void testMethod1(){
        test.startTest();
       
        
        Profile objprofile = [select id from Profile where Name='DGTL Base Profile'];
        user merUser = DGTL_TestDataFactory.createUser(objprofile.Id,'DGTL_Merchandiser');
        insert merUser;
        
        System.runAs(merUser){
            list<Placement_Content__c> list_Content = [SELECT Id,name,Brand__c,Image__c,
                                                       Link__c,Main_Message__c,Page_Name__c,
                                                       Offer_Type__c from  Placement_Content__c];
            list<Placement_Content_Detail__c> list_contentDetail = [SELECT id,name,Slides__c,Asset_Path__c,Copy__c From Placement_Content_Detail__c ];
            list<string> detailId = new list<string>();
            list<string> selContKod = new list<string>();
            detailId.add(list_contentDetail[0].id);
            DGT_cascadeContentCtr.mainReturnDataWpr mainWrapClass = DGT_cascadeContentCtr.fetchContents(list_Content[0].Id);
            DGT_cascadeContentCtr.saveContents(list_Content,list_contentDetail,detailId,true,selContKod,'');
            
            list<DGT_cascadeContentCtr.contentDetWpr> list_contentDetWpr = new list<DGT_cascadeContentCtr.contentDetWpr>();
            DGT_cascadeContentCtr.contentDetWpr detWrap = new DGT_cascadeContentCtr.contentDetWpr();
            DGT_cascadeContentCtr.fieldDataWpr fieldData = new DGT_cascadeContentCtr.fieldDataWpr();
            fieldData.fieldLabel='Copy';
            fieldData.fieldApi='Copy__c';
            list<DGT_cascadeContentCtr.fieldDataWpr> list_fieldData = new list<DGT_cascadeContentCtr.fieldDataWpr>();
            list_fieldData.add(fieldData);
            detWrap.list_PlcConDetFieldData = list_fieldData;
            list_contentDetWpr.add(detWrap);
            
            
            DGT_cascadeContentCtr.addNewPlConDet(list_Content[0].Id,list_contentDetWpr[0]);
            DGT_cascadeContentCtr.promotePlConDets(list_Content[0].Id,list_contentDetWpr);
            
        }
        
        test.stopTest();
        
    }
    static testmethod void deletacce(){
        list<DGTL_Access_Management__c> list_AccessMng = [select id from DGTL_Access_Management__c ];
        delete list_AccessMng;
    }
    static testmethod void testMethod2(){
        
        test.startTest();
       
        
        Profile objprofile = [select id from Profile where Name='DGTL Base Profile'];
        user merUser = DGTL_TestDataFactory.createUser(objprofile.Id,'DGTL_Merchandiser');
        insert merUser;
        
        System.runAs(merUser){
            list<Placement_Content__c> list_Content = [SELECT Id,name,Brand__c,Image__c,
                                                       Link__c,Main_Message__c,Page_Name__c,
                                                       Offer_Type__c from  Placement_Content__c];
            list<Placement_Content_Detail__c> list_contentDetail = [SELECT id,name,Slides__c,Asset_Path__c,Copy__c From Placement_Content_Detail__c ];
            list<string> detailId = new list<string>();
            list<string> selContKod = new list<string>();
            detailId.add(list_contentDetail[0].id);
            DGT_cascadeContentCtr.mainReturnDataWpr mainWrapClass = DGT_cascadeContentCtr.fetchContents(list_Content[0].Id);
            DGT_cascadeContentCtr.saveContents(list_Content,list_contentDetail,detailId,true,selContKod,'');
        }
        test.stopTest();
    } 
    
}