Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset_Path__c</fullName>
        <inlineHelpText>Enter creative delivery shared drive path</inlineHelpText>
        <label>Asset Path</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Copy__c</fullName>
        <inlineHelpText>Enter copy for offer/non-offer placements</inlineHelpText>
        <label>Copy</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Slides__c</fullName>
        <inlineHelpText>Select slide number to differentiate the slides in a carousel</inlineHelpText>
        <label>Slides</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slide 1</fullName>
                </value>
                <value>
                    <fullName>Slide 2</fullName>
                </value>
                <value>
                    <fullName>Slide 3</fullName>
                </value>
                <value>
                    <fullName>Slide 4</fullName>
                </value>
                <value>
                    <fullName>Slide 5</fullName>
                </value>
                <value>
                    <fullName>Slide 6</fullName>
                </value>
                <value>
                    <fullName>Slide 7</fullName>
                </value>
                <value>
                    <fullName>Slide 8</fullName>
                </value>
                <value>
                    <fullName>Slide 9</fullName>
                </value>
                <value>
                    <fullName>Slide 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/classes/DGTL_PlacementContentDetail_HandlerTest.cls
/************************************************************
Name          : DGTL_PlacementContentDetail_HandlerTest
Description   : Test Class for DGTL_PlacementContentDetail_Handler ,DGTL_PlacementContentDetTrgServices,DGTL_PlacementContentDetail_Trigger
*************************************************************/
@isTest
public class DGTL_PlacementContentDetail_HandlerTest {
    
      @TestSetup
    static void testMethod1(){
        DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        Placement_Library__c testLib = DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1,
                                                                                   'VS', 'Home Page', '5 AM', '5 AM',
                                                                                   'Desktop', 'Approved', 'Non Offer', 'mainMsg');
        insert testLib;
        
        list<Placement_Content__c> list_Content = new  list<Placement_Content__c>();
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout.Id, testLib.Id));
        insert list_Content;
        
        list<Placement_Content_Detail__c> list_contentDetail = new List<Placement_Content_Detail__c>();
        Placement_Content_Detail__c contentDetail = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                      false, 'Slide 1', 'asset path', 'Copy text');
        
        Placement_Content_Detail__c contentDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        Placement_Content_Detail__c contentDetail2 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        list_contentDetail.add(contentDetail);
        list_contentDetail.add(contentDetail1);
        list_contentDetail.add(contentDetail2);
        
        Id fieldAccessId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        id taskRecId =  Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Task Creation').getRecordTypeId();

        list<DGTL_Access_Management__c> list_AccessMng = new list<DGTL_Access_Management__c>();
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;','','History Tracking',
                                                                       fieldAccessId,'DGTL_Merchandiser'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;','','History Tracking',
                                                                       fieldAccessId,'DGTL_Copy_Writer'));
         list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;','','',
                                                                       taskRecId,'DGTL_Merchandiser'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;','','',
                                                                       taskRecId,'DGTL_Copy_Writer'));
        
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagmentWithCategory('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                                  'Home Page', 'DGTL_Merchandiser','My Test Group00'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagmentWithCategory('VS','Placement_Content_Detail__c',
                                                                      'Asset_Path__c;Copy__c;Slides__c;Detail Added;Detail Deleted;',
                                                                                  'Home Page', 'DGTL_Copy_Writer','My Test Group00'));
        insert list_AccessMng; 
        
        insert list_contentDetail;
        
        list_contentDetail[0].Slides__c = 'Slide 2'; list_contentDetail[0].Asset_Path__c = 'Slide 2';
        list_contentDetail[1].Slides__c = 'Slide 2'; list_contentDetail[1].Asset_Path__c = 'Slide 2'; 
        list_contentDetail[2].Slides__c = 'Slide 2'; list_contentDetail[2].Asset_Path__c = 'Slide 2';
        update list_contentDetail;
        delete  list_contentDetail[2];
        
    }
    
    
    static testmethod void testMethod2(){
        
        Profile objprofile = [select id from Profile where Name='DGTL Base Profile' LIMIT 1];
        user merUser = DGTL_TestDataFactory.createUser(objprofile.Id,'DGTL_Merchandiser');
        insert merUser;
        
        system.runAs(merUser){
            test.startTest();
            CollaborationGroup myGroup = new CollaborationGroup();
            myGroup.Name='My Test Group00';
            myGroup.CollaborationType='Public'; //can be 'Public' or 'Private'                   
            insert myGroup;
            test.stopTest();
            
        }
    }
    
}