Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Placement_Content__c</fullName>
                    <label>Placement Content</label>
                </value>
                <value>
                    <fullName>Placement_Library__c</fullName>
                    <label>Placement Library</label>
                </value>
                <value>
                    <fullName>Placement_Content_Detail__c</fullName>
                    <label>Placement Content Detail</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Read_Only_Fields__c</fullName>
        <label>Read Only Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Object_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Name</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                    <label>Record ID</label>
                </value>
                <value>
                    <fullName>Placement_layout__c</fullName>
                    <label>Placement Layout</label>
                </value>
                <value>
                    <fullName>Placement_library__c</fullName>
                    <label>Placement Library</label>
                </value>
                <value>
                    <fullName>Image__c</fullName>
                    <label>Image</label>
                </value>
                <value>
                    <fullName>Link__c</fullName>
                    <label>Link</label>
                </value>
                <value>
                    <fullName>Main_Message__c</fullName>
                    <label>Main Message</label>
                </value>
                <value>
                    <fullName>Offer_Type__c</fullName>
                    <label>Offer Type</label>
                </value>
                <value>
                    <fullName>Page_Name__c</fullName>
                    <label>Page Name</label>
                </value>
                <value>
                    <fullName>Position__c</fullName>
                    <label>Position</label>
                </value>
                <value>
                    <fullName>Projected__c</fullName>
                    <label>Projected</label>
                </value>
                <value>
                    <fullName>Shot_Number__c</fullName>
                    <label>Shot Number</label>
                </value>
                <value>
                    <fullName>Style_Info__c</fullName>
                    <label>Style Info</label>
                </value>
                <value>
                    <fullName>S_No__c</fullName>
                    <label>S No</label>
                </value>
                <value>
                    <fullName>Copy_Image__c</fullName>
                    <label>Copy Image</label>
                </value>
                <value>
                    <fullName>Active__c</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Approval_Status__c</fullName>
                    <label>Approval Status</label>
                </value>
                <value>
                    <fullName>Content_Type__c</fullName>
                    <label>Content Type</label>
                </value>
                <value>
                    <fullName>layout_type__c</fullName>
                    <label>Layout Type</label>
                </value>
                <value>
                    <fullName>theme__c</fullName>
                    <label>Theme</label>
                </value>
                <value>
                    <fullName>textbox_width__c</fullName>
                    <label>Textbox Width</label>
                </value>
                <value>
                    <fullName>textbox_background_color__c</fullName>
                    <label>Textbox Background Color</label>
                </value>
                <value>
                    <fullName>text_box_opacity__c</fullName>
                    <label>Text Box Opacity</label>
                </value>
                <value>
                    <fullName>headline_color__c</fullName>
                    <label>Headline color</label>
                </value>
                <value>
                    <fullName>copy_color__c</fullName>
                    <label>Copy Color</label>
                </value>
                <value>
                    <fullName>imagepath__c</fullName>
                    <label>ImagePath</label>
                </value>
                <value>
                    <fullName>image_link__c</fullName>
                    <label>Image Link</label>
                </value>
                <value>
                    <fullName>image_map_path__c</fullName>
                    <label>Image Map Path</label>
                </value>
                <value>
                    <fullName>cta__c</fullName>
                    <label>CTA</label>
                </value>
                <value>
                    <fullName>details_link__c</fullName>
                    <label>Details Link</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DGTL_Bangalore_Commerce_Services</fullName>
                    <label>Bangalore Commerce Services</label>
                </value>
                <value>
                    <fullName>DGTL_Commerce_Operations</fullName>
                    <label>Commerce Operations</label>
                </value>
                <value>
                    <fullName>DGTL_Copy_Writer</fullName>
                    <label>Copy Writer</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Design</fullName>
                    <label>Creative Design</label>
                </value>
                <value>
                    <fullName>DGTL_Digital_Producers</fullName>
                    <label>Digital Producers</label>
                </value>
                <value>
                    <fullName>DGTL_Merchandiser</fullName>
                    <label>Merchandiser</label>
                </value>
                <value>
                    <fullName>DGTL_Offer_Management</fullName>
                    <label>Offer Management</label>
                </value>
                <value>
                    <fullName>DGTL_Angelcard</fullName>
                    <label>Angelcard</label>
                </value>
                <value>
                    <fullName>DGTL_Creative_Operations</fullName>
                    <isActive>false</isActive>
                    <label>Creative Operations</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Compare_Type__c</fullName>
        <label>Compare Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Row_Start__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Check the box if the placement should display in its own row on the mosaic view</inlineHelpText>
        <label>Row Start</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Row_Start__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check the box if the placement should display in its own row on the mosaic view</inlineHelpText>
        <label>Row Start</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Placement Type old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANNER</fullName>
                </value>
                <value>
                    <fullName>CUE</fullName>
                </value>
                <value>
                    <fullName>FEATURE</fullName>
                </value>
                <value>
                    <fullName>OFFER BANNER</fullName>
                </value>
                <value>
                    <fullName>BANNER 1</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 1</label>
                </value>
                <value>
                    <fullName>BANNER 2</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 2</label>
                </value>
                <value>
                    <fullName>BANNER 3</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 3</label>
                </value>
                <value>
                    <fullName>CUE 1</fullName>
                    <isActive>false</isActive>
                    <label>CUE 1</label>
                </value>
                <value>
                    <fullName>CUE 2</fullName>
                    <isActive>false</isActive>
                    <label>CUE 2</label>
                </value>
                <value>
                    <fullName>CUE 3</fullName>
                    <isActive>false</isActive>
                    <label>CUE 3</label>
                </value>
                <value>
                    <fullName>CUE 4</fullName>
                    <isActive>false</isActive>
                    <label>CUE 4</label>
                </value>
                <value>
                    <fullName>CUE 5</fullName>
                    <isActive>false</isActive>
                    <label>CUE 5</label>
                </value>
                <value>
                    <fullName>SUB CUE</fullName>
                    <isActive>false</isActive>
                    <label>SUB CUE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_PlacementContentServices.cls
public class DGTL_PlacementContentServices {
    
    public static list<DGTL_Access_Management__c> getAccessManagement(list<string> str_Brand , String str_objectName) {
        id taskRecId =  Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Task Creation').getRecordTypeId();
        map<String,list<DGTL_Access_Management__c>> map_BrandAccessMgmt = New map<String,list<DGTL_Access_Management__c>>();
        
        list<DGTL_Access_Management__c> list_AccessMgmt = [select name, Team__c,Read_Only_Fields__c,Brands__c 
                                                           from DGTL_Access_Management__c where 
                                                           Brands__c IN : str_Brand  and Read_Only_Fields__c != null 
                                                           AND Object_Name__c =: str_objectName
                                                           AND RecordTypeId =: taskRecId AND Team__c != null];
        
        for(String brand : str_Brand){
            list<DGTL_Access_Management__c> list_BrandAccessMgmt = New list<DGTL_Access_Management__c>();
            for(DGTL_Access_Management__c accessMgmt : list_AccessMgmt){
                if(accessMgmt.Brands__c == brand) list_BrandAccessMgmt.add(accessMgmt);
            }
            map_BrandAccessMgmt.put(brand,list_BrandAccessMgmt);
        }
        
        return list_AccessMgmt;
        
    }
    
    public static map<String,list<DGTL_Access_Management__c>> getAccessManagementMap(list<string> str_Brand,String str_objectName) {
        map<String,list<DGTL_Access_Management__c>> map_BrandAccessMgmt = New map<String,list<DGTL_Access_Management__c>>();
        list<DGTL_Access_Management__c> list_AccessMgmt = getAccessManagement(str_Brand,str_objectName);
        for(String brand : str_Brand){
            list<DGTL_Access_Management__c> list_BrandAccessMgmt = New list<DGTL_Access_Management__c>();
            for(DGTL_Access_Management__c accessMgmt : list_AccessMgmt){
                if(accessMgmt.Brands__c == brand) list_BrandAccessMgmt.add(accessMgmt);
            }
            map_BrandAccessMgmt.put(brand,list_BrandAccessMgmt);
        }
        
        return map_BrandAccessMgmt;
    }
    
    public static void defaultValuesOnBefore(List<Placement_Content__c> list_PayConts,Map<Id,Placement_Content__c> map_PlContOld)
    {
        Set<Id> set_PlacLayIds = New Set<Id>();
        Map<Id,Placement_Layout__c> map_PlacLayout = New Map<Id,Placement_Layout__c>();
        
        //Get all the layout ids
         for(Placement_Content__c pCon : list_PayConts)
        {  
            if(Trigger.isBefore && Trigger.isInsert){
                pCon.Row_Start__c = True;
                pCon.Compare_Type__c = '';
            }
           if(pCon.Id == null || (pCon.Id != null && pCon.Type__c != 'Escalation')){
               system.debug('pCon.Placement_Layout__c--'+pCon.Placement_Layout__c);   system.debug('pCon.Placement_Library__c--'+pCon.Placement_Library__c);
               system.debug('pCon.Type__c--'+pCon.Type__c);   system.debug('pCon.AB_Test_Name__c--'+pCon.AB_Test_Name__c);
                pCon.Unique_Field__c = pCon.Placement_Layout__c + '-'+ pCon.Placement_Library__c +  '-' + pCon.Type__c  + '-' + pCon.AB_Test_Name__c;
            }           
            //Populate Name Field
           // if(map_PlContOld == null || 
             //  (pCon.Placement_Layout__c != map_PlContOld.get(pCon.Id).Placement_Layout__c || 
               // pCon.Placement_type__c != map_PlContOld.get(pCon.Id).Placement_type__c || 
                //pCon.Main_Message__c != map_PlContOld.get(pCon.Id).Main_Message__c)) {
                    set_PlacLayIds.add(pCon.Placement_Layout__c);
                //}
        }
                
        if(set_PlacLayIds.isEmpty()) return;
        for(Placement_Layout__c ply : [SELECT Id,Name,Type__c,Compared_Placement_Layout__c,Page_Types__c FROM Placement_Layout__c WHERE Id IN :set_PlacLayIds]) {            
            map_PlacLayout.put(ply.Id,ply);
        }
        
        for(Placement_Content__c pCon : list_PayConts)
        {
            if(map_PlacLayout.containskey(pCon.Placement_Layout__c))
            {
                //String pCOnName = map_PlacLayIdsNames.get(pCon.Placement_Layout__c);
                String pCOnName = map_PlacLayout.get(pCon.Placement_Layout__c).Name;
                Integer len = pCOnName !=null ? 75 - pCOnName.length() : 0;
                if(pCon.Placement_type__c !=null && len > 0){
                    pCOnName += pCon.Placement_type__c.length() <= len ? ' - '+pCon.Placement_type__c : ' - '+pCon.Placement_type__c.substring(0,len);
                }
                len = pCOnName !=null ? 75 - pCOnName.length() : 0;
                if(pCon.Main_Message__c !=null && len > 0) {  
                    pCOnName += pCon.Main_Message__c.length() <= len ? ' - '+pCon.Main_Message__c : ' - '+pCon.Main_Message__c.substring(0,len);
                }  
                pCon.Name = pCOnName;
                
                // After Tasks are created for ComServ Team -- All the Placements Created except Escallation Content will be defaulted as InActive
                if(pCon.Id == null && pCon.Type__c != 'Escalation' && map_PlacLayout.get(pCon.Placement_Layout__c).Compared_Placement_Layout__c != null){
                    pCon.Active__c = false;
                }
                // checks for LTO'S page type and collection page url
                if(map_PlacLayout.get(pCon.Placement_Layout__c).Page_Types__c != 'LTO' && pCon.Collection_Page_Url__c != null){
                    pCon.Collection_Page_Url__c = null;
                }
            }            
            
        } 
        
    }
    
}