Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Notification</fullName>
        <active>true</active>
        <label>Notification</label>
    </recordTypes>
</CustomObject>

Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/History_Tracking__c.object
<CustomObject>
    <label>History Tracking</label>
    <nameField>
        <displayFormat>HT - {0000000000}</displayFormat>
        <label>History Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content Detail</label>
        <referenceTo>Placement_Content_Detail__c</referenceTo>
        <relationshipLabel>History Tracking</relationshipLabel>
        <relationshipName>History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>History Tracking</relationshipLabel>
        <relationshipName>History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>History Tracking</relationshipLabel>
        <relationshipName>History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_PlacementContent_HandlerTest.cls
/************************************************************
Name          : DGTL_PlacementContent_HandlerTest
Description   : Test Class for DGTL_PlacementContent_Handler,DGTL_PlacementContentServices,
                DGTL_PlacementContentTrgHandler,DGTL_PlacementContent_Trigger
*************************************************************/
@isTest

public class DGTL_PlacementContent_HandlerTest {
  @TestSetup
    static void testMethod1(){
        test.startTest();
        Id fieldAccessId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        id taskRecId =  Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Task Creation').getRecordTypeId();
        id notificationId =  Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Notification').getRecordTypeId();

        list<DGTL_Access_Management__c> list_AccessMng = new list<DGTL_Access_Management__c>();
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c','','History Tracking',
                                                                       fieldAccessId,'DGTL_Merchandiser'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c','','History Tracking',
                                                                       fieldAccessId,'DGTL_Copy_Writer'));
         list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c','','',
                                                                       taskRecId,'DGTL_Merchandiser'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added',
                                                                      'Image__c;Link__c;Main_Message__c;Offer_Type__c','','',
                                                                       taskRecId,'DGTL_Copy_Writer'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagmentWithCategory('VS','Placement_Content__c',
                                                                                  'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added;Active__c',
                                                                                  'Home Page', 'DGTL_Merchandiser','My Test Group00'));
        list_AccessMng.add(DGTL_TestDataFactory.createAccessManagmentWithCategory('VS','Placement_Content__c',
                                                                                  'Image__c;Link__c;Main_Message__c;Offer_Type__c;Placement Added;Active__c',
                                                                                  'Home Page', 'DGTL_Copy_Writer','My Test Group00'));
        insert list_AccessMng; 
        
        DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        Placement_Library__c testLib = DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1,
                                                                                   'VS', 'Home Page', '5 AM', '5 AM',
                                                                                   'Desktop', 'Approved', 'Non Offer', 'mainMsg');
        insert testLib;
        
        Placement_Library__c testLib1 = DGTL_TestDataFactory.createPlacementLibrary(DATE.today()+2, DATE.today()+2,
                                                                                   'VS', 'Home Page', '5 AM', '5 AM',
                                                                                   'Mobile', 'Approved', 'Non Offer', 'mainMsg');
        insert testLib1;
        
        list<Placement_Content__c> list_Content = new  list<Placement_Content__c>();
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout.Id, testLib.Id));
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout.Id, testLib1.Id));
        insert list_Content;
        
        list<History_Tracking__c> list_HistoryRecords = new list<History_Tracking__c>();
        list_HistoryRecords.add(DGTL_TestDataFactory.createOnChangeHisRec('VS','DGTL_Merchandiser','',list_Content[0].id,testLayout.Id));
        insert list_HistoryRecords;
        
        
        
        list<Placement_Content_Detail__c> list_contentDetail = new List<Placement_Content_Detail__c>();
        Placement_Content_Detail__c contentDetail = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                      false, 'Slide 1', 'asset path', 'Copy text');
        
        Placement_Content_Detail__c contentDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        Placement_Content_Detail__c contentDetail2 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        list_contentDetail.add(contentDetail);
        list_contentDetail.add(contentDetail1);
        list_contentDetail.add(contentDetail2);
        
        insert list_contentDetail;
        
        list_Content[0].Main_Message__c = 'ehcfuiygungyifeyghiueww';
        list_Content[0].Active__c = true;
        update list_Content;
        
        list_Content[0].Active__c = false;
        update list_Content;
        
        delete list_Content;
        
        test.stopTest();
        
    }
    
     static testmethod void testMethod2(){
        
        Profile objprofile = [select id from Profile where Name='DGTL Base Profile' LIMIT 1];
        user merUser = DGTL_TestDataFactory.createUser(objprofile.Id,'DGTL_Merchandiser');
        insert merUser;
        
        system.runAs(merUser){
            test.startTest();
            CollaborationGroup myGroup = new CollaborationGroup();
            myGroup.Name='My Test Group00';
            myGroup.CollaborationType='Public'; //can be 'Public' or 'Private'                   
            insert myGroup;
            test.stopTest();
            
        }
    }
    
}