Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Layouts__c</fullName>
        <label>Layouts</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collection_Page_Name__c</fullName>
        <label>Editorial Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Floorset Plan</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Brands__c</field>
                <operation>equals</operation>
                <valueField>DGTL_Floorset_Plan__c.Brands__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Name__c</fullName>
        <label>Test Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_PlacementLayoutTriggerHandler.cls
public class DGTL_PlacementLayoutTriggerHandler 
{
    public static void updateplacementLayoutExtId(List<Placement_Layout__c> list_PayLayOuts,Map<Id,Placement_Layout__c> map_PlcLayOld)
    {
        List<String> list_FloorsetPlanIds = New List<String>();
        Map<String,String> map_FloorsetPlanIdsNames = New Map<String,String>();     
        for(Placement_Layout__c ply : list_PayLayOuts)
        {
            /*if(map_PlcLayOld == Null || (ply.Floorset_Plan__c != map_PlcLayOld.get(ply.Id).Floorset_Plan__c || 
                ply.Page_Types__c != map_PlcLayOld.get(ply.Id).Page_Types__c || ply.Device_Type__c != map_PlcLayOld.get(ply.Id).Device_Type__c || 
                ply.Collection_Page_Name__c != map_PlcLayOld.get(ply.Id).Collection_Page_Name__c || ply.Test_Name__c != map_PlcLayOld.get(ply.Id).Test_Name__c ))*/
                list_FloorsetPlanIds.add(ply.Floorset_Plan__c);
        }
        if(list_FloorsetPlanIds.isEmpty()) return;
        Integer randNum = 5;
        for(DGTL_Floorset_Plan__c flr : [SELECT Id,Name FROM DGTL_Floorset_Plan__c WHERE Id IN :list_FloorsetPlanIds])
        {
            map_FloorsetPlanIdsNames.put(flr.Id,flr.Name);
        }
        
        for(Placement_Layout__c ply : list_PayLayOuts)
        {                
            // updating Name with Floorset Plane Name - page type
            if(map_FloorsetPlanIdsNames.containsKey(ply.Floorset_Plan__c))
            {
                ply.Name = map_FloorsetPlanIdsNames.get(ply.Floorset_Plan__c);  
                ply.Name  += ply.Page_Types__c != null ? ' - '+ ply.Page_Types__c  : '';
                ply.Name += ply.Device_Type__c != null ? ' - '+ ply.Device_Type__c : '' ;
                ply.Name += ply.Test_Name__c != null ? ' - '+ ply.Test_Name__c : '';
            }
            ply.Unique_Id__c = ply.Name;
            
            if(ply.Type__c != null && (ply.Type__c == 'Layout' || ply.Type__c == 'Testing'))
            {
                ply.Unique_Id__c += ' - '+ply.Type__c;   
            }else{
                if(ply.Id != null){
                    ply.Unique_Id__c += ' - '+ply.Type__c + '-'+String.valueof(ply.Id);
                }                        
                else{
                    randNum++;
                    ply.Unique_Id__c += ' - '+ply.Type__c +'-'+ DGTL_DataAccessor.generateRandomString(randNum);
                }
                
            }    
            ply.Unique_Id__c += ply.Device_Type__c != null ? ' - '+ ply.Device_Type__c : '';
            ply.Unique_Id__c += ply.Collection_Page_Name__c != null ? ' - '+ ply.Collection_Page_Name__c : '';
            ply.Unique_Id__c += ply.Test_Name__c != null ? ' - '+ ply.Test_Name__c : '';            
        }
        
    }
    public static void updateFloorsetCalendar(List<Placement_Layout__c> list_PayLayOuts, Map<Id,Placement_Layout__c> map_PlcLayOld, Boolean context)
    {
        set<Id> list_FloorsetIds = new set<Id>();
        string baseurl = System.URL.getSalesforceBaseUrl().toExternalForm();
        map<Id,String> map_FloorsetLayouts = new map<Id,String>(); 
      
        if(context == true) {
            for(Placement_Layout__c lay : map_PlcLayOld.values())
            {
                list_FloorsetIds.add(lay.Floorset_Plan__c);  
            }
        }
        
        else{
            
            for(Placement_Layout__c lay:list_PayLayOuts)
            {
                list_FloorsetIds.add(lay.Floorset_Plan__c);
            } 
        }
        
     
        if(!list_FloorsetIds.isEmpty())
        {
            List<DGTL_Floorset_Plan__c> list_floorset = new List<DGTL_Floorset_Plan__c>();
            for(DGTL_Floorset_Plan__c flr : [select id,Layouts__c from DGTL_Floorset_Plan__c where id in :list_FloorsetIds]){
                map_FloorsetLayouts.put(flr.Id,'');
                list_floorset.add(flr);
           }
    
            for(Placement_Layout__c layout : [select Id,Name,Brands__c,Page_Types__c,Device_Type__c,Floorset_Plan__c from Placement_Layout__c where Floorset_Plan__c in :list_FloorsetIds and Type__c='Layout' and Is_Deleted__c=false])
            {
                string links = map_FloorsetLayouts.get(layout.Floorset_Plan__c);
                links += '<br/>';
                links += '<a href="'+baseurl+'/lightning/n/Layouts?c__brand='+layout.Brands__c+'&c__pagetype='+layout.Page_Types__c+'&c__device='+layout.Device_Type__c+'&c__floorset='+layout.Floorset_Plan__c+'">'+layout.Page_Types__c+' - '+layout.Device_Type__c+'</a>';
                links += '<br/>';
                map_FloorsetLayouts.put(layout.Floorset_Plan__c,links);
            }
            
            for(DGTL_Floorset_Plan__c flr : list_floorset)
            {
                flr.Layouts__c = map_FloorsetLayouts.get(flr.Id);    
            }
    
            update list_floorset;
        }
        
        
    }
    
       
}