Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Minute__c</fullName>
        <label>Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Hour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>12 AM</fullName>
                </value>
                <value>
                    <fullName>1 AM</fullName>
                </value>
                <value>
                    <fullName>2 AM</fullName>
                </value>
                <value>
                    <fullName>3 AM</fullName>
                </value>
                <value>
                    <fullName>4 AM</fullName>
                </value>
                <value>
                    <fullName>5 AM</fullName>
                    <default>true</default>
                    <label>5 AM</label>
                </value>
                <value>
                    <fullName>6 AM</fullName>
                </value>
                <value>
                    <fullName>7 AM</fullName>
                </value>
                <value>
                    <fullName>8 AM</fullName>
                </value>
                <value>
                    <fullName>9 AM</fullName>
                </value>
                <value>
                    <fullName>10 AM</fullName>
                </value>
                <value>
                    <fullName>11 AM</fullName>
                </value>
                <value>
                    <fullName>12 PM</fullName>
                </value>
                <value>
                    <fullName>1 PM</fullName>
                </value>
                <value>
                    <fullName>2 PM</fullName>
                </value>
                <value>
                    <fullName>3 PM</fullName>
                </value>
                <value>
                    <fullName>4 PM</fullName>
                </value>
                <value>
                    <fullName>5 PM</fullName>
                </value>
                <value>
                    <fullName>6 PM</fullName>
                </value>
                <value>
                    <fullName>7 PM</fullName>
                </value>
                <value>
                    <fullName>8 PM</fullName>
                </value>
                <value>
                    <fullName>9 PM</fullName>
                </value>
                <value>
                    <fullName>10 PM</fullName>
                </value>
                <value>
                    <fullName>11 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Floorset Plan</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Brands__c</field>
                <operation>equals</operation>
                <valueField>DGTL_Floorset_Plan__c.Brands__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Name__c</fullName>
        <label>Test Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTLFloorsetPlanServices.cls
/* Name        : DGTLFloorsetPlanServices
 * Description : This class is used in DGTLFloorsetPlanTriggerHandler.cls
 * Author      : Vidya Sagar
 * 
 */
public without sharing class DGTLFloorsetPlanServices {

     
     /*   Description : This method is called in DGTLFloorsetPlanTriggerHandler, beforeinsert method
      *                 This method is used to update name with and unique name field with concatenation of brand, date,time and type 
      *   Param       : floorsetPlanList - trigger.new values before insert 
      */
     public static void defaultFieldValues(List<DGTL_Floorset_Plan__c > floorsetPlanList){
           
         Map<Id,DGTL_Floorset_Plan__c> oldMap_Floorset = trigger.isUpdate ? (Map<Id,DGTL_Floorset_Plan__c>)trigger.oldMap : null ; 
         for(DGTL_Floorset_Plan__c flr : floorsetPlanList){
             if(oldMap_Floorset != null && !oldMap_Floorset.isEmpty()){
                 // error message to restrict brand change 
                 if(flr.Brands__c != oldMap_Floorset.get(flr.Id).Brands__c)
                    flr.Brands__c.addError('Brand cannot be changed');
             }
             string strTime ;
             if(flr.Minute__c != null){
                 strTime = flr.Time__c.substringBefore(' ')+':'+ flr.Minute__c+' '+flr.Time__c.substringAfter(' ');             
             }else{
                 flr.Minute__c = '00';
                 strTime = flr.Time__c.substringBefore(' ')+':00 '+flr.Time__c.substringAfter(' ');             
             }
            flr.Name = flr.Brands__c+' - '+flr.Date__c.Month()+'/'+flr.Date__c.Day()+'/'+flr.Date__c.Year()+' - '+strTime+' - '+flr.Type__c; 
            //flr.Unique_Name__c = flr.Brands__c+' - '+flr.Date__c.Month()+'/'+flr.Date__c.Day()+'/'+flr.Date__c.Year()+' - '+strTime+' - '+flr.Type__c; 
            flr.Unique_Name__c = flr.Brands__c+' - '+flr.Date__c.Month()+'/'+flr.Date__c.Day()+'/'+flr.Date__c.Year()+' - '+strTime; // request change for remove type in unique field
        }
        
     }
     
     /*   This method is called in DGTLFloorsetPlanTriggerHandler, afterUpdate method
      *   This method is used to update Layout name when floorset date/type/time changed
      *   @ Param floorsetIds : Floorset Ids 
      */
    /* public static void updateLayoutNames(List<DGTL_Floorset_Plan__c > floorsetPlanList){
         system.debug('----floorsetPlanList--updateLayoutNames---'+floorsetPlanList);
         List<Id> list_UpdatedFloorsetIds = new List<Id>();
         Map<Id,DGTL_Floorset_Plan__c> oldMap_Floorset = trigger.isUpdate ? (Map<Id,DGTL_Floorset_Plan__c>)trigger.oldMap : null ; 
         system.debug('----oldMap_Floorset--'+oldMap_Floorset);
         for(DGTL_Floorset_Plan__c flr : floorsetPlanList){
              system.debug('----check name--'+flr.Name+'---'+oldMap_Floorset.get(flr.Id).Name);
                 if(flr.Name != oldMap_Floorset.get(flr.Id).Name)
                    list_UpdatedFloorsetIds.add(flr.Id);
          }
          system.debug('----list_UpdatedFloorsetIds--'+list_UpdatedFloorsetIds);
          if(!list_UpdatedFloorsetIds.isEmpty()){
             List<Placement_Layout__c> list_UpdateLayouts = new List<Placement_Layout__c>();
             for(Placement_Layout__c lay : [select id,Name,Page_Types__c,Device_Type__c,Test_Name__c,Unique_Id__c from Placement_Layout__c where Floorset_Plan__c IN :list_UpdatedFloorsetIds]){
                    list_UpdateLayouts.add(lay);
                    system.debug('----lay--'+lay);
                }
              if(!list_UpdateLayouts.isEmpty())
                 Update list_UpdateLayouts;
          } 
         
        
     } */
}