Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Layouts__c</fullName>
        <label>Layouts</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/classes/DGTL_PlacementLayoutTest.cls
@isTest
public class DGTL_PlacementLayoutTest {
    
    public static testMethod void testupdateFloorsetCalendar(){
        
        
        DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        delete testLayout;
        DGTL_Floorset_Plan__c testFloorset2 = [select id, layouts__c from DGTL_Floorset_Plan__c where id =: testFloorset.id];
        system.assertEquals(null, testFloorset2.layouts__c);
        
    }
    
}