Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/DGTL_Task__c.object
<CustomObject>
    <label>Digital Task</label>
    <nameField>
        <displayFormat>TSK-{0000000000}</displayFormat>
        <label>Digital Task No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Desktop__c</fullName>
        <label>Desktop</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Floorset/Update</label>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Digital Task</relationshipLabel>
        <relationshipName>Digital_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Day_View</fullName>
        <active>true</active>
        <label>Day View</label>
    </recordTypes>
</CustomObject>

Digital/classes/DGTL_DayViewControllerTest.cls
@isTest
public class DGTL_DayViewControllerTest {
    
    @testSetup
    static void setupData(){
        Id recordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='DGTL_Task__c' AND DeveloperName='Day_View'].Id;
       
        DGTL_Floorset_Plan__c vsFloorsetPlan1 = DGTL_TestDataFactory.createFloorsetPlan('VS',DATE.today(),'5 AM','Update');
        insert vsFloorsetPlan1;
                
        DGTL_Task__c task = new DGTL_Task__c(Desktop__c='Test',RecordTypeId=recordTypeId,Floorset_Plan__c=vsFloorsetPlan1.Id);
        insert task;
    }
    
    public static testMethod void getTaskId(){
        Id floorsetId = [SELECT Id FROM DGTL_Floorset_Plan__c LIMIT 1].Id;
        Test.startTest();
        DGTL_DayViewController.getTaskId(floorsetId);
        Test.stopTest();
        DGTL_Floorset_Plan__c vsFloorsetPlan2 = DGTL_TestDataFactory.createFloorsetPlan('VS',DATE.today(),'2 AM','Update');
        insert vsFloorsetPlan2;
        DGTL_DayViewController.getTaskId(vsFloorsetPlan2.Id);
    }

}