Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Page</fullName>
                </value>
                <value>
                    <fullName>Landing Page</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S_No__c</fullName>
        <label>S No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Digital/objects/Placement_KOD__c.object
<CustomObject>
    <label>Placement&amp;KOD</label>
    <nameField>
        <displayFormat>L&amp;K{00000}</displayFormat>
        <label>Layout&amp;KOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements&amp;KODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipName>Layouts_KODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Layouts_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Placements_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Library</relationshipLabel>
        <relationshipName>Placement_Library</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Types</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_MultiKODLinkControllerTest.cls
@isTest
public class DGTL_MultiKODLinkControllerTest {
    
    @testSetup
    static void setupData(){
        List<KOD__c> kodList = new List<KOD__c>();
        kodList.add(new KOD__c(Offer_Status__c='Approved',Name='Test1'));
        kodList.add(new KOD__c(Offer_Status__c='Cancelled',Name='Test2'));
        
        insert kodList;
        
        DGTL_Floorset_Plan__c vsFloorsetPlan = DGTL_TestDataFactory.createFloorsetPlan('VS',DATE.today().addDays(-1),'2 AM','Update');
        insert vsFloorsetPlan;
        
        Placement_Layout__c layout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',vsFloorsetPlan.Id, 'Layout');
        insert layout;
        
        Placement_Library__c plibrary = DGTL_TestDataFactory.createPlacementLibrary(DATE.today().addDays(-1), DATE.today().addDays(1), 'VS', 'Home Page', '1 AM', '6 AM', 'Desktop', 'Approved', 'Offer', 'Main Message - Desktop');
        insert plibrary;
        
        List<Placement_Content__c> pContList = DGTL_TestDataFactory.createPlacementContentlist(null,'', 1,
                                                                                               null,'','Video',
                                                                                               'Controlled','Feature','Offer');
        pContList[0].S_No__c = 1;
        pContList[0].Placement_Library__c = plibrary.Id;
        pContList[0].Main_Message__c = 'Main Message 1 - Desktop';
        pContList[0].Placement_Layout__c = layout.Id;
        pContList[0].Page_Name__c =layout.Page_Types__c; 
        
        insert pContList;
        
        Placement_KOD__c pKod = new Placement_KOD__c(Placement_Content__c=pContList[0].Id,KOD__c=kodList[0].Id);
        insert pKod;
    }
    
    static testMethod void fetchKODDetails(){
        List<KOD__c> kodList = [SELECT Id FROM KOD__c LIMIT 2];
        Test.startTest();
        for(KOD__c kod : kodList){
            try{
                DGTL_MultiKODLinkController.fetchKODDetails(kod.Id);
            }catch(AuraException ae){
                System.debug('AuraException====='+ae.getMessage());
            }
        }
        Test.stopTest();
        try{
            DGTL_MultiKODLinkController.fetchKODDetails(kodList[0].Id+'a');
        }catch(AuraException ae){
            System.debug('AuraException====='+ae.getMessage());
        }
    }
    
    static testMethod void fetchPlacementKODs(){
        Placement_Content__c pc = [SELECT Id FROM Placement_Content__c LIMIT 1];
        Test.startTest();
        DGTL_MultiKODLinkController.fetchPlacementKODs(pc.Id);
        Test.stopTest();
    }
    
    static testMethod void linkPlacementKODs(){
        List<Id> kodIdAddList = new List<Id>();
        Id pcId = [SELECT Id FROM Placement_Content__c LIMIT 1].Id;
        for(KOD__c kod : [SELECT Id FROM KOD__c]){
            kodIdAddList.add(kod.Id);
        }
        List<Id> kodIdRemoveList = new List<Id>{[SELECT Id FROM KOD__c WHERE Offer_Status__c='Approved' LIMIT 1].Id};
        
        Test.startTest();
        DGTL_MultiKODLinkController.linkPlacementKODs(pcId, kodIdAddList, kodIdRemoveList);
        Test.stopTest();
        
        try{
            DGTL_MultiKODLinkController.linkPlacementKODs(pcId, new List<Id>(), new List<Id>{pcId});  //with wrong Id
        }catch(AuraException ae){
            System.debug('ae----'+ae.getMessage());
        }
        
        
    }

}