Digital/objects/DGTL_Task__c.object
<CustomObject>
    <label>Digital Task</label>
    <nameField>
        <displayFormat>TSK-{0000000000}</displayFormat>
        <label>Digital Task No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Floorset_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Floorset/Update</label>
        <referenceTo>DGTL_Floorset_Plan__c</referenceTo>
        <relationshipLabel>Digital Task</relationshipLabel>
        <relationshipName>Digital_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Day_View</fullName>
        <active>true</active>
        <label>Day View</label>
    </recordTypes>
</CustomObject>

Digital/classes/DGTL_DayViewController.cls
public class DGTL_DayViewController {
	
    @AuraEnabled
    public static Id getTaskId(String floorsetPlanId){
        Id taskId;
        try{
            taskId = [SELECT Id FROM DGTL_Task__c WHERE RecordType.DeveloperName='Day_View' AND Floorset_Plan__c = :floorsetPlanId LIMIT 1].Id;
        }catch(Exception e){
            if(!Test.isRunningTest())
            throw new AuraException('No Records Found!');
        }
        return taskId;
    }
}