Digital/objects/DGTL_Access_Management__c.object
<CustomObject>
    <description>This object is used to control access level of user on DIGITAL Application/objects/fields/pages</description>
    <label>Access Management</label>
    <nameField>
        <displayFormat>ACMG-{000000}</displayFormat>
        <label>DGTL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/DGTL_Floorset_Plan__c.object
<CustomObject>
    <label>Floorset/Update</label>
    <nameField>
        <label>Floorset Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floorset/Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Floorset</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/DGTL_Task__c.object
<CustomObject>
    <label>Digital Task</label>
    <nameField>
        <displayFormat>TSK-{0000000000}</displayFormat>
        <label>Digital Task No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Placement_Content__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy__c</fullName>
        <label>Copy</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipName>Task_Digital</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__r.Name</formula>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Escalation</fullName>
        <active>true</active>
        <label>Escalation</label>
    </recordTypes>
</CustomObject>

Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>TEXT(Placement_Layout__r.Brands__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Placement_Content_Self__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content Self</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Page_Type__c</fullName>
        <formula>TEXT(Placement_Layout__r.Page_Types__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Placement_Content__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy__c</fullName>
        <inlineHelpText>Enter copy for offer/non-offer placements</inlineHelpText>
        <label>Copy</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Placement_Content_Detail_Self__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content Detail</label>
        <referenceTo>Placement_Content_Detail__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Slides__c</fullName>
        <inlineHelpText>Select slide number to differentiate the slides in a carousel</inlineHelpText>
        <label>Slides</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slide 1</fullName>
                </value>
                <value>
                    <fullName>Slide 2</fullName>
                </value>
                <value>
                    <fullName>Slide 3</fullName>
                </value>
                <value>
                    <fullName>Slide 4</fullName>
                </value>
                <value>
                    <fullName>Slide 5</fullName>
                </value>
                <value>
                    <fullName>Slide 6</fullName>
                </value>
                <value>
                    <fullName>Slide 7</fullName>
                </value>
                <value>
                    <fullName>Slide 8</fullName>
                </value>
                <value>
                    <fullName>Slide 9</fullName>
                </value>
                <value>
                    <fullName>Slide 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Placement_Content__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Upload one or more screen cap(s) of a product image to be featured on site</inlineHelpText>
        <label>CAD/Shot/Screen Cap</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Placement Type old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANNER</fullName>
                </value>
                <value>
                    <fullName>CUE</fullName>
                </value>
                <value>
                    <fullName>FEATURE</fullName>
                </value>
                <value>
                    <fullName>OFFER BANNER</fullName>
                </value>
                <value>
                    <fullName>BANNER 1</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 1</label>
                </value>
                <value>
                    <fullName>BANNER 2</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 2</label>
                </value>
                <value>
                    <fullName>BANNER 3</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 3</label>
                </value>
                <value>
                    <fullName>CUE 1</fullName>
                    <isActive>false</isActive>
                    <label>CUE 1</label>
                </value>
                <value>
                    <fullName>CUE 2</fullName>
                    <isActive>false</isActive>
                    <label>CUE 2</label>
                </value>
                <value>
                    <fullName>CUE 3</fullName>
                    <isActive>false</isActive>
                    <label>CUE 3</label>
                </value>
                <value>
                    <fullName>CUE 4</fullName>
                    <isActive>false</isActive>
                    <label>CUE 4</label>
                </value>
                <value>
                    <fullName>CUE 5</fullName>
                    <isActive>false</isActive>
                    <label>CUE 5</label>
                </value>
                <value>
                    <fullName>SUB CUE</fullName>
                    <isActive>false</isActive>
                    <label>SUB CUE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_PlacementContentUpdateTest.cls
/************************************************************
Name          : DGTL_PlacementContentUpdateTest
Description   : Test Class for DGTL_PlacementContentUpdate
*************************************************************/
@isTest
public class DGTL_PlacementContentUpdateTest {
    @TestSetup
    static void initialize(){
        
        DGTL_Floorset_Plan__c testFloorset = DGTL_TestDataFactory.createFloorsetPlan('VS', Date.today(), '5 AM', 'Floorset');
        insert testFloorset;
        
        Placement_Layout__c testLayout = DGTL_TestDataFactory.createPlacementLayout('VS','Home Page','Desktop',testFloorset.Id, 'Layout');
        insert testLayout;
        
        Placement_Library__c testLib = DGTL_TestDataFactory.createPlacementLibrary(DATE.today(), DATE.today()+1,
                                                                                   'VS', 'Home Page', '5 AM', '5 AM',
                                                                                   'Desktop', 'Approved', 'Non Offer', 'mainMsg');
        insert testLib;
        
        list<Placement_Content__c> list_Content = new  list<Placement_Content__c>();
        list_Content.add(DGTL_TestDataFactory.createPlacementContent(testLayout.Id, testLib.Id));
        insert list_Content;
        
        Placement_Content__c escalation = DGTL_TestDataFactory.createEscalationPlacementContent(testLayout.Id, null);
        escalation.Placement_Content_Self__c = list_Content[0].Id;
        insert escalation;
        
        list<Placement_Content_Detail__c> list_contentDetail = new List<Placement_Content_Detail__c>();
        Placement_Content_Detail__c contentDetail = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                      false, 'Slide 1', 'asset path', 'Copy text');
        
        Placement_Content_Detail__c contentDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        Placement_Content_Detail__c contentDetail2 = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                       false, 'Slide 1', 'asset path1', 'Copy text1');
        list_contentDetail.add(contentDetail);
        list_contentDetail.add(contentDetail1);
        list_contentDetail.add(contentDetail2);
        insert list_contentDetail;
        
        list<Placement_Content_Detail__c> list_contentDetailEsc = new List<Placement_Content_Detail__c>();
        Placement_Content_Detail__c contentDetail01 = DGTL_TestDataFactory.createPlacementContentDetail(escalation.Id, null,
                                                                                                        false, 'Slide 1', 'asset path1', 'Copy text1');
        contentDetail01.Placement_Content_Detail_Self__c =list_contentDetail[0].Id; 
        
        Placement_Content_Detail__c contentDetail11 = DGTL_TestDataFactory.createPlacementContentDetail(escalation.Id, null,
                                                                                                        false, 'Slide 1', 'asset path1', 'Copy text1');
        contentDetail11.Placement_Content_Detail_Self__c =list_contentDetail[1].Id; 
        
        Placement_Content_Detail__c contentDetail12 = DGTL_TestDataFactory.createPlacementContentDetail(escalation.Id, null,
                                                                                                        false, 'Slide 1', 'asset path1', 'Copy text1');
        contentDetail12.Placement_Content_Detail_Self__c =list_contentDetail[2].Id; 
        contentDetail12.Is_Deleted__c = true;
        list_contentDetailEsc.add(contentDetail01);
        list_contentDetailEsc.add(contentDetail11);
        list_contentDetailEsc.add(contentDetail12);        
        insert list_contentDetailEsc;
        
        Id RecordTypeId = Schema.SObjectType.DGTL_Access_Management__c.getRecordTypeInfosByName().get('Field Access').getRecordTypeId();
        DGTL_Access_Management__c contentAccessRec = DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content__c','Image__c;Link__c;','Image__c;Link__c;',
                                                                                                '','DGTL Main',RecordTypeId,'DGTL_Merchandiser');
        insert contentAccessRec;
        DGTL_Access_Management__c contentDetailAccessRec = DGTL_TestDataFactory.createAccessManagment('VS','Placement_Content_Detail__c','Copy__c;Slides__c;','Copy__c;Slides__c;',
                                                                                                      '','Layout - Content Detail',RecordTypeId,'DGTL_Merchandiser');
        insert contentDetailAccessRec;
        
        DGTL_Task__c digitalTask = DGTL_TestDataFactory.createEscalationTask(list_Content[0].Id);
        insert digitalTask;
    }
    
    static testmethod void testMethod1(){
        Profile objprofile = [select id from Profile where Name='DGTL Base Profile' LIMIT 1];
        user merUser = DGTL_TestDataFactory.createUser(objprofile.Id,'DGTL_Merchandiser');
        insert merUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'DGTL_Merchandiser'];
        PermissionSetAssignment psAssign = DGTL_TestDataFactory.createPermissionSetAssgn(merUser.Id,ps.Id);
        insert psAssign;
        Group grp = new Group();
        grp.name = 'VS-Escalation Queue';
        grp.Type = 'Regular'; 
        Insert grp; 
        //Create Group Member
        GroupMember grpMem1 = new GroupMember();
        grpMem1.UserOrGroupId = merUser.Id;
        grpMem1.GroupId = grp.Id;
        Insert grpMem1;
        System.runAs(merUser){ 
            Test.startTest(); 
            
            DGTL_PlacementContentUpdate.DGTL_UpdateWraper DGTL_ResWraper = New DGTL_PlacementContentUpdate.DGTL_UpdateWraper();        
            list<Placement_Content__c> list_Content = [SELECT ID,Image__c,name,Link__c,Placement_Content_Self__c,Brand__c,Placement_Page_Type__c,LastModifiedDate,
                                                       Has_Unapproved__c,Placement_Layout__c,Type__c,Placement_Library__c,LastModifiedBy.Name,
                                                       Main_Message__c,Offer_Type__c,Content_Type__c from Placement_Content__c where Type__c='Controlled'];
            
            Placement_Content__c escalationContent = [SELECT ID,Image__c,name,Link__c,Placement_Content_Self__c,Brand__c,Placement_Page_Type__c,LastModifiedDate,
                                                      Has_Unapproved__c,Type__c,Placement_Layout__c,Placement_Library__c,LastModifiedBy.Name,
                                                      Main_Message__c,Offer_Type__c,Content_Type__c from Placement_Content__c
                                                      where Type__c='Escalation'];
            list<Placement_Content_Detail__c> contentDetail = [SELECT ID,name,Link_Text__c,Placement_Content__c,Sub_Type__c,Asset_Path__c,LastModifiedDate,
                                                               Copy__c,Slides__c,Is_Deleted__c,Placement_Content_Detail_Self__c,LastModifiedBy.Name,Comments__c
                                                               from Placement_Content_Detail__c];
            list<Placement_Content_Detail__c> list_DetelePlacementContentDetail = new list<Placement_Content_Detail__c>();
            list<Placement_Content_Detail__c> list_DetelePlacementContentDetailOld = new list<Placement_Content_Detail__c>();
            
            list<String> contentFields = new list<String>();
            contentFields.add('Image__c');        contentFields.add('Link__c');
            
            map<String,String> map_DetailWriteFields = new  map<String,String>();
            map_DetailWriteFields.put('Copy__c','Copy__c');        map_DetailWriteFields.put('Slides__c','Slides__c');
            
            map<String,String> map_WriteFields = new  map<String,String>();
            map_WriteFields.put('Image__c','Image__c');        map_WriteFields.put('Link__c','Link__c');
            map_WriteFields.put('Main_Message__c','Main_Message__c');        map_WriteFields.put('Offer_Type__c','Offer_Type__c');
            
            DGTL_PlacementContentUpdate.initialize(list_Content[0].Id);
            
            list_Content[0].Main_Message__c = 'hgfiufbgquwebucfhbhqeiubcf';
            list_Content[0].Offer_Type__c ='Non Offer';
            // list_Content[0].Link__c ='73654jhbjwgdywg';
            DGTL_PlacementContentUpdate.saveChanges(contentDetail,list_DetelePlacementContentDetail,
                                                    list_DetelePlacementContentDetailOld, map_DetailWriteFields, map_WriteFields,
                                                    true, list_Content[0],contentFields);
            
            contentDetail[0].Copy__c = 'new Copy Text';        contentDetail[1].Slides__c ='Slide 2';
            Placement_Content_Detail__c contentDetailNew = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                             false, 'Slide 1', 'asset path Text', 'Copy text');
            Placement_Content_Detail__c newDet  = new Placement_Content_Detail__c();
            newDet.Id = null;
            contentDetail.add(newDet);        contentDetail.add(contentDetailNew);
            
            DGTL_PlacementContentUpdate.saveChanges(contentDetail,list_DetelePlacementContentDetail,
                                                    list_DetelePlacementContentDetailOld, map_DetailWriteFields, map_WriteFields,
                                                    false, escalationContent,contentFields); 
            
            DGTL_Task__c taskaskObj = [SELECT ID,name,Brand__c,Changed_Content_Fields__c from  DGTL_Task__c  LIMIT 1];
            DGTL_PlacementContentUpdate.sendEscalationEmail(taskaskObj);
            
            Test.stopTest();
            
        }
    }
    
    static testmethod void testMethod2(){
        Test.startTest(); 
        DGTL_PlacementContentUpdate.DGTL_UpdateWraper DGTL_ResWraper = New DGTL_PlacementContentUpdate.DGTL_UpdateWraper();        
        Placement_Content__c escalationContent = [SELECT ID,Image__c,name,Link__c,Placement_Content_Self__c,Brand__c,Placement_Page_Type__c,LastModifiedDate,
                                                  Has_Unapproved__c,Type__c,Placement_Layout__c,Placement_Library__c,LastModifiedBy.Name,
                                                  Main_Message__c,Offer_Type__c,Content_Type__c from Placement_Content__c
                                                  where Type__c='Escalation'];
        list<Placement_Content_Detail__c> contentDetail = [SELECT ID,name,Link_Text__c,Placement_Content__c,Sub_Type__c,Asset_Path__c,LastModifiedDate,
                                                           Copy__c,Slides__c,Is_Deleted__c,LastModifiedBy.Name,Placement_Content_Detail_Self__c,Comments__c
                                                           from Placement_Content_Detail__c];
        list<Placement_Content_Detail__c> list_DetelePlacementContentDetail = new list<Placement_Content_Detail__c>();
        list<Placement_Content_Detail__c> list_DetelePlacementContentDetailOld = new list<Placement_Content_Detail__c>();
        
        DGTL_PlacementContentUpdate.initialize(escalationContent.Id);
        list<String> contentFields = new list<String>();        contentFields.add('Image__c');        contentFields.add('Link__c');
        
        map<String,String> map_DetailWriteFields = new  map<String,String>();
        map_DetailWriteFields.put('Copy__c','Copy__c');        map_DetailWriteFields.put('Slides__c','Slides__c');
        
        map<String,String> map_WriteFields = new  map<String,String>();
        map_WriteFields.put('Image__c','Image__c');        map_WriteFields.put('Link__c','Link__c');
        
        Placement_Content_Detail__c delDetail = DGTL_TestDataFactory.createPlacementContentDetail(escalationContent.Id, null,
                                                                                                  false, 'Slide 1', 'asset path Text', 'Copy text');
        Placement_Content_Detail__c delDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(escalationContent.Id, null,
                                                                                                   false, 'Slide 1', 'asset path Text', 'Copy text');
        
        delDetail.Is_Deleted__c = false; upsert delDetail;        Placement_Content_Detail__c detNew = new Placement_Content_Detail__c();
        list_DetelePlacementContentDetail.add(delDetail);   list_DetelePlacementContentDetail.add(delDetail1);   
        list_DetelePlacementContentDetailOld.add(delDetail);
        contentDetail.add(detNew);
        
        contentDetail[0].Copy__c ='hefbhuygwefuyywe';
        escalationContent.Main_Message__c = 'jhbfhebfuewgbfuyy';
        DGTL_PlacementContentUpdate.saveChanges(contentDetail,list_DetelePlacementContentDetail,list_DetelePlacementContentDetailOld,
                                                map_DetailWriteFields, map_WriteFields,false, escalationContent,contentFields);
        
        DGTL_Task__c taskaskObj = [SELECT ID,name,Brand__c,Changed_Content_Fields__c from  DGTL_Task__c  LIMIT 1];
        DGTL_PlacementContentUpdate.sendEscalationEmail(taskaskObj);
        DGTL_PlacementContentUpdate.sendParentContentAndDetail(escalationContent);
        Test.stopTest();
    }
    
    static testmethod void testMethod3(){
        Test.startTest(); 
        list<Placement_Content__c> list_Content = [SELECT ID,Image__c,name,Link__c,Placement_Content_Self__c,Brand__c,Placement_Page_Type__c,LastModifiedDate,
                                                   Has_Unapproved__c,Placement_Layout__c,Type__c,Placement_Library__c,LastModifiedBy.Name,
                                                   Main_Message__c,Offer_Type__c,Content_Type__c from Placement_Content__c where Type__c='Controlled'];
        
        Placement_Content__c escalationContent = [SELECT ID,Image__c,name,Link__c,Placement_Content_Self__c,Brand__c,Placement_Page_Type__c,LastModifiedDate,
                                                  Has_Unapproved__c,Type__c,Placement_Layout__c,Placement_Library__c,LastModifiedBy.Name,
                                                  Main_Message__c,Offer_Type__c,Content_Type__c from Placement_Content__c
                                                  where Type__c='Escalation'];
        list<Placement_Content_Detail__c> contentDetail = [SELECT ID,name,Link_Text__c,Placement_Content__c,Sub_Type__c,Asset_Path__c,LastModifiedDate,
                                                           Copy__c,Slides__c,Is_Deleted__c,Placement_Content_Detail_Self__c,LastModifiedBy.Name,Comments__c
                                                           from Placement_Content_Detail__c];
        list<Placement_Content_Detail__c> list_DetelePlacementContentDetail = new list<Placement_Content_Detail__c>();
        list<Placement_Content_Detail__c> list_DetelePlacementContentDetailOld = new list<Placement_Content_Detail__c>();
        
        list<String> contentFields = new list<String>();
        contentFields.add('Image__c');        contentFields.add('Link__c');
        
        map<String,String> map_DetailWriteFields = new  map<String,String>();
        map_DetailWriteFields.put('Copy__c','Copy__c');        map_DetailWriteFields.put('Slides__c','Slides__c');
        
        map<String,String> map_WriteFields = new  map<String,String>();
        map_WriteFields.put('Image__c','Image__c');        map_WriteFields.put('Link__c','Link__c');
        
        DGTL_PlacementContentUpdate.initialize(list_Content[0].Id);
        
        //-----------------
        Placement_Content_Detail__c delDetail = DGTL_TestDataFactory.createPlacementContentDetail(escalationContent.Id, null,
                                                                                                  false, 'Slide 1', 'asset path Text', 'Copy text');
        Placement_Content_Detail__c delDetail1 = DGTL_TestDataFactory.createPlacementContentDetail(escalationContent.Id, null,
                                                                                                   false, 'Slide 1', 'asset path Text', 'Copy text');
        
        delDetail.Is_Deleted__c = false; upsert delDetail;        Placement_Content_Detail__c detNew = new Placement_Content_Detail__c();
        list_DetelePlacementContentDetail.add(delDetail);   list_DetelePlacementContentDetail.add(delDetail1); 
        //--------------------
        list_DetelePlacementContentDetailOld.add(delDetail);
        DGTL_PlacementContentUpdate.saveChanges(contentDetail,list_DetelePlacementContentDetail,
                                                list_DetelePlacementContentDetailOld, map_DetailWriteFields, map_WriteFields,
                                                true, list_Content[0],contentFields);
        
        contentDetail[0].Copy__c = 'new Copy Text';        contentDetail[1].Slides__c ='Slide 2';
        Placement_Content_Detail__c contentDetailNew = DGTL_TestDataFactory.createPlacementContentDetail(list_Content[0].Id, null,
                                                                                                         false, 'Slide 1', 'asset path Text', 'Copy text');
        Placement_Content_Detail__c newDet  = new Placement_Content_Detail__c();
        newDet.Id = null;
        contentDetail.add(newDet);        contentDetail.add(contentDetailNew);
        
        DGTL_PlacementContentUpdate.saveChanges(contentDetail,list_DetelePlacementContentDetail,
                                                list_DetelePlacementContentDetailOld, map_DetailWriteFields, map_WriteFields,
                                                false, escalationContent,contentFields); 
        
        DGTL_Task__c taskaskObj = [SELECT ID,name,Brand__c,Changed_Content_Fields__c from  DGTL_Task__c  LIMIT 1];
        DGTL_PlacementContentUpdate.sendEscalationEmail(taskaskObj);
        
        DGTL_PlacementContentUpdate.sendParentContentAndDetail(escalationContent);
        Test.stopTest();
    }
}