Digital/objects/Digital_Live_Users__c.object
<CustomObject>
    <label>Digital Live Users</label>
    <nameField>
        <displayFormat>LU-{0000000000}</displayFormat>
        <label>Digital Live Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Live Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_Poll_Time__c</fullName>
        <label>Last Poll Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

Digital/classes/DGTL_DeleteLiveUsersScheduledBatch.cls
/* Name        : DGTL_DeleteLiveUsersScheduledBatch
 * Description : This class is used to schedule to delete old live users data
 * Author      : Vidya Sagar 
 */
public class DGTL_DeleteLiveUsersScheduledBatch implements Schedulable, Database.Stateful {
    
    /*    
    public Database.querylocator start(Database.BatchableContext BC){ 
            DateTime lastPollDeldatetime = system.now().addMinutes(-30);
            return Database.getQueryLocator('SELECT Id,Last_Poll_Time__c FROM Digital_Live_Users__c WHERE Last_Poll_Time__c<=:lastPollDeldatetime');
        
    }
    
    public void execute(Database.BatchableContext BC, List<Digital_Live_Users__c> scope){        
		delete scope;        
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
    */
    
    //schedule 
    public void execute(SchedulableContext SC) {        
       //Database.executeBatch(new DGTL_DeleteLiveUsersScheduledBatch());   
       DateTime lastPollDeldatetime = system.now().addMinutes(-30);
       delete [SELECT Id,Last_Poll_Time__c FROM Digital_Live_Users__c WHERE Last_Poll_Time__c<=:lastPollDeldatetime];
    }
   
}