Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compared_Placement_Layout__c</fullName>
        <formula>Placement_Layout__r.Compared_Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compared Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Placement_Layout__r.Date_Formula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Compared_Placement_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compared Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Floorset_Plan__r.Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_No__c</fullName>
        <formula>Floorset_Plan__r.Time_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Placement Type old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANNER</fullName>
                </value>
                <value>
                    <fullName>CUE</fullName>
                </value>
                <value>
                    <fullName>FEATURE</fullName>
                </value>
                <value>
                    <fullName>OFFER BANNER</fullName>
                </value>
                <value>
                    <fullName>BANNER 1</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 1</label>
                </value>
                <value>
                    <fullName>BANNER 2</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 2</label>
                </value>
                <value>
                    <fullName>BANNER 3</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 3</label>
                </value>
                <value>
                    <fullName>CUE 1</fullName>
                    <isActive>false</isActive>
                    <label>CUE 1</label>
                </value>
                <value>
                    <fullName>CUE 2</fullName>
                    <isActive>false</isActive>
                    <label>CUE 2</label>
                </value>
                <value>
                    <fullName>CUE 3</fullName>
                    <isActive>false</isActive>
                    <label>CUE 3</label>
                </value>
                <value>
                    <fullName>CUE 4</fullName>
                    <isActive>false</isActive>
                    <label>CUE 4</label>
                </value>
                <value>
                    <fullName>CUE 5</fullName>
                    <isActive>false</isActive>
                    <label>CUE 5</label>
                </value>
                <value>
                    <fullName>SUB CUE</fullName>
                    <isActive>false</isActive>
                    <label>SUB CUE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_WebRemoter.cls
public class DGTL_WebRemoter {
    
    @AuraEnabled
    public static List<Placement_Content__c> getFutureContents(String contentId){
       List<Placement_Content__c> plcList = new List<Placement_Content__c>();
      
        Placement_Content__c pc = [SELECT Type__c,Id,Placement_Layout__r.Date_Formula__c,Placement_Layout__r.Time_No__c,Placement_Library__c 
                                   FROM Placement_Content__c 
                                   WHERE Id=:contentId];
        Date layoutDate = pc.Placement_Layout__r.Date_Formula__c;
        Decimal layoutTime = pc.Placement_Layout__r.Time_No__c;
        try{
            for(Placement_Content__c futureContent : [SELECT Id,Name,Main_Message__c, Placement_Layout__r.Name,CreatedDate,Placement_Library__c,Compared_Placement_Layout__c,
                                                      Placement_Layout__r.Date_Formula__c,Placement_Layout__r.Time_No__c From Placement_Content__c
                                                      WHERE Type__c =: pc.Type__c AND Active__c = TRUE AND Placement_Library__c=:pc.Placement_Library__c 
                                                      AND Placement_Layout__r.Type__c='Layout'
                                                      AND (Placement_Layout__r.Date_Formula__c >=:layoutDate 
                                                          OR (Placement_Layout__r.Date_Formula__c =:layoutDate 
                                                              AND Placement_Layout__r.Time_No__c >:layoutTime))
                                                      ORDER BY Placement_Layout__r.Date_Formula__c,Placement_Layout__r.Time_No__c])
            {
                plcList.add(futureContent);
            } 
            System.debug('plcList==='+plcList.size());
        }catch(QueryException qe){
            throw new AuraException('No records found.');
        }catch(Exception e){
            throw new AuraException(e.getMessage());
        }
        
        
        return plcList;
    }

}