Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Placement_Content__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <description>This Field is to specify the date to get snapshots for different days.</description>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_Snapshot_SCH.cls
global class DGTL_Snapshot_SCH implements Schedulable {
    
    global void execute(SchedulableContext sc){  
        
         String layoutFields = getAllFields('Placement_Layout__c');
        //Select all the layouts and layout contents where the type="layout" and LastModifiedDate =today()
        list<Placement_Layout__c> layoutList = new list<Placement_Layout__c>();        
        String listQuery = 'SELECT id' + layoutFields;
		string layoutType = 'Layout';
        Date today = system.today();
        listQuery += ' FROM Placement_Layout__c  WHERE Type__c =:layoutType and LastModifiedDate >=:today';
        layoutList = Database.query(listQuery);   
        Savepoint sp = Database.setSavepoint();     
        try{
            
            map<string, list<string>> map_ChildsToClone = new map<string, list<string>>();
            map_ChildsToClone.put('Placement_Layout__c', new list<string>{'Placement_Content__c'});
            map_ChildsToClone.put('Placement_Content__c', new list<string>{'Placement_Content_Detail__c'});
            map<string, map<string, string>> map_StaticValues = new map<string, map<string, string>>();
            String todayDate = String.valueOf(date.today());
            map_StaticValues.put('Placement_Layout__c', new map<string, string>{'Type__c' => 'Snapshot', 'Snapshot_Date__c' => todayDate});

            DGTL_GenericMultiLevelClone.deepCloneBatched(layoutList, 
                                                        map_ChildsToClone, 
                                                        map_StaticValues );     
        }catch(exception e){
            Database.rollback(sp);
            system.debug('Error messages : '+e.getMessage());
        }        
    }   
     // Method to get list of field api's as string from diffrent object
    public static String getAllFields(String objectApiName){
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(objectApiName).getDescribe().fields.getMap();
        string queryFields = '';
        for(String s : fieldMap.keyset()){
            if(!queryFields.contains(s) && s.toUpperCase() != 'ID') queryFields += ',' + s;
        }
        return queryFields;
    } 
}