Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Collection_Page_Url__c</fullName>
        <inlineHelpText>Add collection page URLs for collection Header and collection cue placements.  Enter URL without live site details. For e.g. enter “/vs/newarrivals/shop-collection” without “https://victoriassecret.com/”</inlineHelpText>
        <label>Collection Page Url</label>
        <length>20768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_type__c</fullName>
        <inlineHelpText>Select the type of placement from the drop down. E.g. Banner, Cue, feature, Site Majority Offer etc.</inlineHelpText>
        <label>Placement type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Cue</fullName>
                </value>
                <value>
                    <fullName>Site Majority Offer</fullName>
                </value>
                <value>
                    <fullName>Floating Cue/Collection Cue</fullName>
                </value>
                <value>
                    <fullName>Collection Header</fullName>
                </value>
                <value>
                    <fullName>Stack Header</fullName>
                </value>
                <value>
                    <fullName>Product Page Header</fullName>
                </value>
                <value>
                    <fullName>Offer Copy</fullName>
                </value>
                <value>
                    <fullName>OLCO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collection_Page_Url__c</fullName>
        <inlineHelpText>Add collection page URLs for collection Header and collection cue placements.  Enter URL without live site details. For e.g. enter “/vs/newarrivals/shop-collection” without “https://victoriassecret.com/”</inlineHelpText>
        <label>Collection Page Url</label>
        <length>20768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Minute__c</fullName>
        <label>End Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <inlineHelpText>Select if the placement is offer/non offer from the drop down. If placement is an offer type then select KODs in the next field</inlineHelpText>
        <label>Offer/Non-offer</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Non Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Types</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement_type__c</fullName>
        <inlineHelpText>Select the type of placement from the drop down. E.g. Banner, Cue, feature, Site Majority Offer etc.</inlineHelpText>
        <label>Placement type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Cue</fullName>
                </value>
                <value>
                    <fullName>Site Majority Offer</fullName>
                </value>
                <value>
                    <fullName>Floating Cue/Collection Cue</fullName>
                </value>
                <value>
                    <fullName>Collection Header</fullName>
                </value>
                <value>
                    <fullName>Stack Header</fullName>
                </value>
                <value>
                    <fullName>Product Page Header</fullName>
                </value>
                <value>
                    <fullName>Offer Copy</fullName>
                </value>
                <value>
                    <fullName>OLCO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Minute__c</fullName>
        <label>Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_PlacementLibraryTriggerHandler.cls
/* Name        : DGTL_PlacementLibraryTriggerHandler
 * Description : This class is used in DGTL_PlacementLibraryTrigger.trigger
 * Author      : Vidya Sagar
 * 
 */
public class DGTL_PlacementLibraryTriggerHandler 
{
    
     /*    Description : This method is called in DGTL_PlacementLibraryTrigger, beforeinsert and before update
      *                  This method is used to update name with concatenation 
      *    Param       : list_PlcLibraryNew - list trigger.new values,  map_PlcLibraryOld - map of old values
      */
    public static void updateDefaults(List<Placement_Library__c> list_PlcLibraryNew,Map<Id,Placement_Library__c> map_PlcLibraryOld)
    {
        for(Placement_Library__c pll : list_PlcLibraryNew)
        {
            if(pll.Start_Minute__c == null)
              pll.Start_Minute__c = '00';
            if(pll.End_Minute__c == null)
              pll.End_Minute__c = '00';
            if(pll.Offer_Type__c == 'Non Offer')
            {
                pll.Status__c = 'Approved';
            }
            else if(pll.Offer_Type__c == 'Offer' && ((map_PlcLibraryOld == Null) || (map_PlcLibraryOld != Null && map_PlcLibraryOld.get(pll.Id).Offer_Type__c != 'Offer')))
            {
                pll.Status__c = 'Submitted';
            }           
            // updating Name with Brand-PageType-placement type
            if(map_PlcLibraryOld == Null || (pll.Brands__c != map_PlcLibraryOld.get(pll.Id).Brands__c || pll.Page_Types__c != map_PlcLibraryOld.get(pll.Id).Page_Types__c || pll.Placement_type__c != map_PlcLibraryOld.get(pll.Id).Placement_type__c || pll.Main_Message__c != map_PlcLibraryOld.get(pll.Id).Main_Message__c))
            {
                pll.Name = '';
                if(pll.Brands__c != null )
                {
                    pll.Name = pll.Brands__c;
                }
                if(pll.Page_Types__c != null )
                {
                    pll.Name += ' - '+ pll.Page_Types__c;
                }
                if(pll.Placement_type__c != null )
                {
                    pll.Name += ' - '+ pll.Placement_type__c;
                }
                if(pll.Main_Message__c !=null)
                {
                    Integer len = 0;
                    if(pll.Name !=null){
                        len = 75 - pll.Name.length();
                    }                        
                    if(pll.Main_Message__c.length() <= len)
                    {
                        pll.Name += ' - '+pll.Main_Message__c;
                    }else{
                        pll.Name +=  ' - '+pll.Main_Message__c.substring(0,len);
                    } 
                }
            }
            
            // checks for LTO's page types and collection page url
            if(pll.Page_Types__c != 'LTO' && pll.Collection_Page_Url__c != null && pll.Page_Types__c != 'Editorials')
               {
                   pll.Collection_Page_Url__c = null;
               }
        }
    }
    
     /*    Description : This method is called in DGTL_PlacementLibraryTrigger after insert 
      *                  cloning content details when library is cloned 
      *    Param       : list_PlcLibraryNew - list trigger.new values
      */
     
    public static void cloneContentDetails(List<Placement_Library__c> list_PlcLibraryNew){
        list<Id> list_ClonedIds = new list<Id>();
        map<Id,Id> map_CloneIdNewId = new map<Id,Id>();
        // trigger.new for loop
        for(Placement_Library__c pll : list_PlcLibraryNew)
        {
            // check for if library is cloned
            if(pll.isClone()){                
                list_ClonedIds.add(pll.getCloneSourceId());
                map_CloneIdNewId.put(pll.getCloneSourceId(),pll.Id);
            }
        }
        if(!list_ClonedIds.isEmpty()){
            Placement_Content_Detail__c obj_ContDetail = new Placement_Content_Detail__c();
            list<Placement_Content_Detail__c> list_ContDetails = new list<Placement_Content_Detail__c>();
            list<Placement_Content_Detail__c> list_OldContDetails = new list<Placement_Content_Detail__c>(); 
            // get content details related to library
            string soql_ContDetail =  DGTL_DataAccessor.getSobjectSoql(obj_ContDetail)+' AND Placement_Library__c IN :list_ClonedIds';
            soql_ContDetail = soql_ContDetail.remove('CloneSourceId,');
            // get content details of old library
            list_OldContDetails = Database.query(soql_ContDetail);
            for(Placement_Content_Detail__c contDet : list_OldContDetails){ 
                // clone content detail
                Placement_Content_Detail__c contDetail = contDet.clone();
                contDetail.Placement_Library__c = map_CloneIdNewId.get(contDet.Placement_Library__c);
                contDetail.Placement_Content__c = null;
                contDetail.OwnerId = UserInfo.getUserId();
                list_ContDetails.add(contDetail);
            }
            // insert cloned content details
            if(!list_ContDetails.isEmpty()){
                insert list_ContDetails;
            }
            
        }
    }
    
}