Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Editorial_Name__c</fullName>
        <formula>Placement_Layout__r.Collection_Page_Name__c</formula>
        <label>Editorial Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <inlineHelpText>Enter position number for the placements to show in a sequence in layout. Leave empty for non-floating cue placements.</inlineHelpText>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Brands__c</fullName>
        <inlineHelpText>Select the brand from the drop down: E.g. VS, PINK, Beauty, Marketplace</inlineHelpText>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DGTL_Brands</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Editorial_Name__c</fullName>
        <description>Indicates the Editorial name when page type is Editorial</description>
        <label>Editorial Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Types__c</fullName>
        <inlineHelpText>Select appropriate Home, Landing, Editorials or LTO page type from the drop down, based on what is being built</inlineHelpText>
        <label>Page Types</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brands__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DGTL_Page_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <inlineHelpText>Enter position number for the placements to show in a sequence in layout. Leave empty for non-floating cue placements.</inlineHelpText>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

Digital/globalValueSets/DGTL_Brands.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PINK</fullName>
    </customValue>
    <customValue>
        <fullName>VS</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Swim</fullName>
        <isActive>false</isActive>
        <label>Swim</label>
    </customValue>
    <masterLabel>DGTL Brands</masterLabel>
</GlobalValueSet>

Digital/globalValueSets/DGTL_Page_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>LTO</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Spotlight</fullName>
    </customValue>
    <customValue>
        <fullName>Editorials</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty Home Page</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge LP</fullName>
    </customValue>
    <customValue>
        <fullName>New LP</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Card LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bras LP</fullName>
    </customValue>
    <customValue>
        <fullName>Panties LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sport LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Beauty LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Accessories LP</fullName>
    </customValue>
    <customValue>
        <fullName>VS Swim LP</fullName>
    </customValue>
    <customValue>
        <fullName>Sale LP</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts LP</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Tops LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bottoms LP</fullName>
    </customValue>
    <customValue>
        <fullName>Outfits LP</fullName>
    </customValue>
    <customValue>
        <fullName>Fragrance LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Body LP</fullName>
    </customValue>
    <customValue>
        <fullName>Lip LP</fullName>
    </customValue>
    <customValue>
        <fullName>PINK LP</fullName>
    </customValue>
    <customValue>
        <fullName>Bikinis LP</fullName>
    </customValue>
    <customValue>
        <fullName>Styles LP</fullName>
    </customValue>
    <customValue>
        <fullName>Inspo LP</fullName>
    </customValue>
    <masterLabel>DGTL Page Types</masterLabel>
</GlobalValueSet>

Digital/classes/DGTL_SearchContFromLibrary.cls
/*****
 * Name         : DGTL_SearchContFromLibrary
 * Description  : This Class is used to create contents from library and to display in table
 * Author       : Vidya Sagar 
 * Component    : This class is controller for lightning compoenent DGTL_SearchContInLibrary.cmp
****/
public class DGTL_SearchContFromLibrary {
    
    /*
	*   Description : This Method is used to add search/filter with input fields(brand,page type,main message) from library 
	*	Component helper method : searchContentToHpr
    *   return : list of layout with size 1
	*/
    @AuraEnabled
    public static List<Placement_Library__c> fetchFilterValues()
    {
        Placement_Library__c obj = new Placement_Library__c();
		List<Placement_Library__c> list_LibraryearchFilter = new List<Placement_Library__c>{obj};
        return list_LibraryearchFilter;
    }
    
    /*
	*   Description             :This Method is used to get list of library, when user clicks on search button
	*	Component helper method : fetchLibraryJsHpr
	*   Param                   : lib_search - library object with brand,page type,main message and editorial name to search 
	*   return                  : return list of library 
	*/
    @AuraEnabled(cacheable=true)
    public static list<Placement_Library__c> fetchLibrary(Placement_Library__c lib_search)
    {
               
        List<Placement_Library__c> list_Library = new List<Placement_Library__c>();
        Placement_Library__c obj_libFields = new Placement_Library__c();
        // checks for Editorials page type
        if(lib_search.Page_Types__c == 'Editorials'){ 
            String libraryQuery = DGTL_DataAccessor.getSobjectSoql(new Placement_Library__c());
            libraryQuery += ' AND Brands__c =\''+lib_search.Brands__c+'\' AND Page_Types__c =\''+lib_search.Page_Types__c+'\''  ; 
            // checks for main message
            if(string.isNotBlank(lib_search.Main_Message__c)) libraryQuery += ' AND Main_Message__c like \'%'+lib_search.Main_Message__c+'%\'' ;
            //checks for editorial name
            if(string.isNotBlank(lib_search.Editorial_Name__c)){
               libraryQuery += ' AND Editorial_Name__c like \'%'+lib_search.Editorial_Name__c+'%\' Order by Position__c';
            }
            list_Library = Database.query(libraryQuery); system.debug('libraryQuery--'+libraryQuery);
        } else{
            list_Library = DGTL_DataAccessor.getLibraryList(DGTL_DataAccessor.getSobjectSoql(obj_libFields), lib_search.Brands__c, lib_search.Page_Types__c, lib_search.Start_Date__c, null, null,null,lib_search.Main_Message__c);       
        }
        return list_Library;
    }
    /*
	*   Description             : This Method is used to Create contents from selectded library, when user clicks on Add Contents
	*	Component helper method : addContsHpr
	*   Param                   : lst_SelectedContIds - selectded libraries ids to create content, pLayoutId - palacement layout id 
	*   Return                  : returns list of DGTL_WrapperClasses.contentWprNew
	*/
    @AuraEnabled
    public static list<DGTL_WrapperClasses.contentWprNew> getSelectedConts(List<string> lst_SelectedContIds,string pLayoutId)
    {
        try{
            list<DGTL_WrapperClasses.contentWprNew> list_cWpr = new list<DGTL_WrapperClasses.contentWprNew>();
        List<Placement_Library__c> list_library = new List<Placement_Library__c>();
        list<Placement_Content__c> list_Contents = new list<Placement_Content__c>();
        Placement_Content_Detail__c obj_Cont_Detail = new Placement_Content_Detail__c();
        list<Placement_Content_Detail__c> list_ContDetail = new list<Placement_Content_Detail__c>();
        list<Placement_Content_Detail__c> list_ContDetailCloned = new list<Placement_Content_Detail__c>();
        string contDetail_soql = DGTL_DataAccessor.getSobjectSoql(obj_Cont_Detail);
        Placement_Library__c obj_Lib = new Placement_Library__c();        
        string lib_soql = DGTL_DataAccessor.getSobjectSoql(obj_Lib);
        lib_soql += ' AND Id In : lst_SelectedContIds';
        // fetch selected libraries
        list_library = Database.query(lib_soql); 
        // creatining content from selected libraries
        list_Contents = DGTL_DataAccessor.createContentsFromLibrary(list_library, DGTL_DataAccessor.getLibraryCopyFieldset());
        for(Placement_Content__c cont :list_Contents)
        {
            cont.Placement_Layout__c = pLayoutId;
            cont.Name='Test';
            system.debug('---pLayoutId--'+cont.Placement_Layout__c);
        }
        // inserting contents 
        insert list_Contents; 
        string cont_soql = DGTL_DataAccessor.getSobjectSoql(new Placement_Content__c()) + ' AND Id In:list_Contents';
        // cloning content details
         contDetail_soql +=  ' AND Placement_Library__c In : lst_SelectedContIds';
         list_ContDetail = Database.query(contDetail_soql);
        for(Placement_Content_Detail__c details : list_ContDetail){
               Placement_Content_Detail__c newDetail = new Placement_Content_Detail__c();
               newDetail = details.clone(false, false, false, false);
               list_ContDetailCloned.add(newDetail);
            }
        for(Placement_Content__c cont : Database.query(cont_soql))
        {
            DGTL_WrapperClasses.contentWprNew cWpr = new DGTL_WrapperClasses.contentWprNew();
            cWpr.pContentRec = cont;
            cWpr.conId = cont.Id; 
            cWpr.errorStatus = 'Success';
            list_cWpr.add(cWpr);
            for(Placement_Content_Detail__c details :list_ContDetailCloned){
                if(details.Placement_Library__c != null && details.Placement_Library__c == cont.Placement_Library__c)
                {
                    details.Placement_Library__c = null;
                    details.Placement_Content__c = cont.Id;
                }
            }
        }
        // creating content details
        if(!list_ContDetailCloned.isEmpty())
        {
            insert list_ContDetailCloned;
            system.debug('-list_ContDetailCloned--'+list_ContDetailCloned);
        }
       return list_cWpr;
        }catch(Exception ex){
            system.debug('---'+ex.getMessage());
            return null;
        }
        
    }

}