Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Compared_Placement_Layout__c</fullName>
        <formula>Placement_Layout__r.Compared_Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compared Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Placement_Layout__r.Date_Formula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to related the Test and Contingency placements with the parent placements.</description>
        <label>Parent Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content (Parent Content)</relationshipLabel>
        <relationshipName>Parent_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <label>Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_type__c</fullName>
        <inlineHelpText>Select the type of placement from the drop down. E.g. Banner, Cue, feature, Site Majority Offer etc.</inlineHelpText>
        <label>Placement type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Cue</fullName>
                </value>
                <value>
                    <fullName>Site Majority Offer</fullName>
                </value>
                <value>
                    <fullName>Floating Cue/Collection Cue</fullName>
                </value>
                <value>
                    <fullName>Collection Header</fullName>
                </value>
                <value>
                    <fullName>Stack Header</fullName>
                </value>
                <value>
                    <fullName>Product Page Header</fullName>
                </value>
                <value>
                    <fullName>Offer Copy</fullName>
                </value>
                <value>
                    <fullName>OLCO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Controlled</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Takedown</fullName>
                </value>
                <value>
                    <fullName>AB Test</fullName>
                </value>
                <value>
                    <fullName>Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Content_Detail__c.object
<CustomObject>
    <label>Placement Content Detail</label>
    <nameField>
        <displayFormat>PCD-{000000000}</displayFormat>
        <label>Placement Content Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placement Content Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Layout__c</fullName>
        <formula>Placement_Content__r.Placement_Layout__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Placement Layout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Library</label>
        <referenceTo>Placement_Library__c</referenceTo>
        <relationshipLabel>Placement Content Details</relationshipLabel>
        <relationshipName>Placement_Content_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Placement_Content__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

Digital/objects/Placement_Layout__c.object
<CustomObject>
    <label>Placement Layout</label>
    <nameField>
        <label>Placement Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Compared_Placement_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compared Placement Layout</label>
        <referenceTo>Placement_Layout__c</referenceTo>
        <relationshipLabel>Placement Layout</relationshipLabel>
        <relationshipName>Placement_Layout</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Formula__c</fullName>
        <formula>Floorset_Plan__r.Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_No__c</fullName>
        <formula>Floorset_Plan__r.Time_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Layout</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/objects/Placement_Library__c.object
<CustomObject>
    <label>Placement Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Main_Message__c</fullName>
        <inlineHelpText>Enter concise main message for the placement. Used as placement identifier everywhere.</inlineHelpText>
        <label>Main Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement_type__c</fullName>
        <inlineHelpText>Select the type of placement from the drop down. E.g. Banner, Cue, feature, Site Majority Offer etc.</inlineHelpText>
        <label>Placement type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Cue</fullName>
                </value>
                <value>
                    <fullName>Site Majority Offer</fullName>
                </value>
                <value>
                    <fullName>Floating Cue/Collection Cue</fullName>
                </value>
                <value>
                    <fullName>Collection Header</fullName>
                </value>
                <value>
                    <fullName>Stack Header</fullName>
                </value>
                <value>
                    <fullName>Product Page Header</fullName>
                </value>
                <value>
                    <fullName>Offer Copy</fullName>
                </value>
                <value>
                    <fullName>OLCO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Placement Type old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANNER</fullName>
                </value>
                <value>
                    <fullName>CUE</fullName>
                </value>
                <value>
                    <fullName>FEATURE</fullName>
                </value>
                <value>
                    <fullName>OFFER BANNER</fullName>
                </value>
                <value>
                    <fullName>BANNER 1</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 1</label>
                </value>
                <value>
                    <fullName>BANNER 2</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 2</label>
                </value>
                <value>
                    <fullName>BANNER 3</fullName>
                    <isActive>false</isActive>
                    <label>BANNER 3</label>
                </value>
                <value>
                    <fullName>CUE 1</fullName>
                    <isActive>false</isActive>
                    <label>CUE 1</label>
                </value>
                <value>
                    <fullName>CUE 2</fullName>
                    <isActive>false</isActive>
                    <label>CUE 2</label>
                </value>
                <value>
                    <fullName>CUE 3</fullName>
                    <isActive>false</isActive>
                    <label>CUE 3</label>
                </value>
                <value>
                    <fullName>CUE 4</fullName>
                    <isActive>false</isActive>
                    <label>CUE 4</label>
                </value>
                <value>
                    <fullName>CUE 5</fullName>
                    <isActive>false</isActive>
                    <label>CUE 5</label>
                </value>
                <value>
                    <fullName>SUB CUE</fullName>
                    <isActive>false</isActive>
                    <label>SUB CUE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Digital/classes/DGTL_MultiContentDelete.cls
/**
* @description 			DGTL_MultiContentDelete - Used fot multi Content Delete - Component Name - DGTL_MultiContentDelete.
* @author       		Namratha P.
* @Created_date         Feb 2020.
* @Revised_date			March 11 2020 - Namratha P.
*/
public class DGTL_MultiContentDelete {
    
/**
* @description  getRelatedPlacements - this Initilizes the Component - DGTL_MultiContentDelete.
* @author       Namratha P , Revised - March 11 2020 - Namratha P.
* @param        content - recives a Content record which is selected for Delete.
* @return       DGTL_MultiContentDeleteWrapper - returns related contents associated with same Library as the selected Content.
*/
    @AuraEnabled
    public static DGTL_MultiContentDeleteWrapper getRelatedPlacements(Placement_Content__c content){
        List<Placement_Content__c> list_PlacementContents =  new list<Placement_Content__c>();
        DGTL_MultiContentDeleteWrapper wrapper = new DGTL_MultiContentDeleteWrapper();
        Date layoutDate;
        Decimal layoutTime;
        String type = content.Type__c;
        List<String> list_Type = new List<String>{'AB Test','Takedown','Contingency'};
            try{
                if(content != null && content.Placement_Library__c != null){
                    
                    for(Placement_Content__c typeContent : [SELECT 
                                                            Id,Name,Main_Message__c,Placement_type__c,Parent_Content__c,
                                                            Compared_Placement_Layout__c,Placement_Layout__c,
                                                            Placement_Layout__r.Date_Formula__c,Type__c,
                                                            Placement_Layout__r.Time_No__c 
                                                            FROM Placement_Content__c 
                                                            WHERE 
                                                            Id =:content.Id OR 
                                                            (
                                                                Parent_Content__c =: content.Id AND 
                                                                (
                                                                    Type__c IN:list_Type
                                                                )
                                                            )
                                                           ])
                    { // get associated AB Test,Takedown,Contingency records
                        if((typeContent.Parent_Content__c == content.Id) && list_Type.contains(typeContent.Type__c))
                            wrapper.list_nonControlled.add(typeContent);
                        
                        if(typeContent.Id == content.Id){ // get date and time of layout to get records from next layouts
                            layoutDate = typeContent.Placement_Layout__r.Date_Formula__c;
                            layoutTime = typeContent.Placement_Layout__r.Time_No__c;                             
                        }
                    }
                    // get Related contentes associated with the content with same Lib ID
                    for(Placement_Content__c contentInst : [SELECT 
                                                            Id,Name,Main_Message__c,Placement_Library__c,Compared_Placement_Layout__c,
                                                            Placement_Layout__r.Date_Formula__c,Placement_Layout__r.Time_No__c,
                                                            Placement_Layout__r.Type__c
                                                            FROM Placement_Content__c 
                                                            WHERE 
                                                            Type__c=:type AND 
                                                            Placement_Library__c=:content.Placement_Library__c AND 
                                                            Placement_Layout__r.Type__c ='Layout' AND 
                                                            (Placement_Layout__r.Date_Formula__c >=:layoutDate OR 
                                                             (
                                                                 Placement_Layout__r.Date_Formula__c =:layoutDate AND 
                                                                 Placement_Layout__r.Time_No__c >:layoutTime
                                                             )
                                                            )])
                    {
                        if(contentInst.Compared_Placement_Layout__c == null) wrapper.list_Contents.add(contentInst);
                        // add locked/ Processed Contents into list to display
                        else wrapper.list_LockedContents.add(contentInst);
                    }
                }
            }catch(exception e){
                system.debug('Error fetching related contents : '+e.getMessage());
            }      
        return wrapper;
    }
    
    
/**
* @description  deletePlacements - deletes contents with associated 'Takedown, AB Test and Contengency'- DGTL_MultiContentDelete.
* @author       Namratha P ,  Feb 2020.
* @param        list_Contents - recives a list of Content record which is selected for Delete.
* @return       String - returns Success if deletion was successfull.
*/
    @AuraEnabled
    public static String deletePlacements(List<Placement_Content__c> list_Contents){
        Set<Id> ids = new Set<Id>();
        List<Placement_Content__c> list_ValidContents = new List<Placement_Content__c>();
        for(Placement_Content__c content : list_Contents){
            if(content.Id != null) {
                ids.add(content.Id);
                list_ValidContents.add(content);
            }
        }
        
        // get all ABTest and Take Down records
        for(Placement_Content__c abOrTakeown : [SELECT id,name,Parent_Content__c FROM Placement_Content__c WHERE Parent_Content__c in:ids])
        {
            ids.add(abOrTakeown.Parent_Content__c);
            list_ValidContents.add(abOrTakeown);
        }
        
        //get All Detail Records for deleting
        list<Placement_Content_Detail__c> list_Details = [SELECT id,name FROM Placement_Content_Detail__c WHERE Placement_Content__c in:ids];
        
        if(list_Details.size() > 0) delete list_Details;
        if(list_ValidContents.size() > 0) delete list_ValidContents;
        
        return 'Success';
    }
    
    public class DGTL_MultiContentDeleteWrapper{
        
        @AuraEnabled public List<Placement_Content__c> list_Contents {get;set;}
        @AuraEnabled public List<Placement_Content__c> list_LockedContents {get;set;}
        @AuraEnabled public List<Placement_Content__c> list_nonControlled {get;set;}       
        
        public DGTL_MultiContentDeleteWrapper(){
            list_Contents = new List<Placement_Content__c>();
            list_LockedContents = new List<Placement_Content__c>();
            list_nonControlled = new List<Placement_Content__c>();
        }
    }
    
}