Digital/objects/Placement_Content__c.object
<CustomObject>
    <label>Placement Content</label>
    <nameField>
        <label>Placement Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select one or more approved KODs if the placement is an offer type. Use search icon in the dropdown to filter further.</inlineHelpText>
        <label>KOD</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>KOD__c.Offer_Status__c</field>
                <operation>equals</operation>
                <value>APPROVED</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KOD__c</referenceTo>
        <relationshipLabel>Placement Content</relationshipLabel>
        <relationshipName>Placement_Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/objects/Placement_KOD__c.object
<CustomObject>
    <label>Placement&amp;KOD</label>
    <nameField>
        <displayFormat>L&amp;K{00000}</displayFormat>
        <label>Layout&amp;KOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements&amp;KODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>KOD__c</fullName>
        <label>KOD</label>
        <referenceTo>KOD__c</referenceTo>
        <relationshipName>Layouts_KODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placement_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Content</label>
        <referenceTo>Placement_Content__c</referenceTo>
        <relationshipLabel>Placements&amp;KODs</relationshipLabel>
        <relationshipName>Layouts_KODs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Digital/classes/DGTL_MultiKODLinkController.cls
public class DGTL_MultiKODLinkController {
    
    @AuraEnabled
    public static String fetchKODDetails(String kodId){
        String kodName= '';
        try{
           KOD__c kod = [SELECT Name,Offer_Status__c FROM KOD__c WHERE Id = :kodId];
            if(kod.Offer_Status__c.equalsIgnoreCase('APPROVED')){
                kodName = kod.Name;
            }else{
                throw new AuraException('KOD has not been approved');
            }
        }catch(Exception e){
            throw new AuraException(e.getMessage());
        }
        return kodName;
    }
    
    @AuraEnabled
    public static List<Map<String,String>> fetchPlacementKODs(String contentId){
        List<Map<String,String>> placementKodMapList = new List<Map<String,String>>();
        
        for(Placement_KOD__c pKod : [SELECT KOD__r.Name,KOD__c FROM Placement_KOD__c 
                                     WHERE Placement_Content__c = :contentId 
                                     AND KOD__c != null])
        {
            Map<String,String> placementKodMap = new Map<String,String>();
            placementKodMap.put('name',pKod.KOD__r.Name);
            placementKodMap.put('id',pKod.KOD__c);
            placementKodMapList.add(placementKodMap);
        }
        return placementKodMapList;
    }
    
     @AuraEnabled
    public static void linkPlacementKODs(String contentId, List<String> kodIds, List<String> removedKODs){
        System.debug('removedKODs-----'+removedKODs);
        System.debug('kodIds-----'+kodIds);
        List<Placement_KOD__c> pKodList = new List<Placement_KOD__c>();
        Set<Id> liveKodIdSet = new Set<Id>();
        
        if(kodIds.size() > 0){
            for(Placement_KOD__c pKOD : [SELECT KOD__c FROM Placement_KOD__c 
                                         WHERE Placement_Content__c = :contentId 
                                         AND KOD__c IN :kodIds])
            {
                liveKodIdSet.add(pKOD.KOD__c);
            }
            
            for(String kodId : kodIds){
                if(!liveKodIdSet.contains(kodId)) pKodList.add(new Placement_KOD__c(Placement_Content__c = contentId, KOD__c = kodId));
            }
        }        
        
        
        try{
            if(pKodList.size() > 0) insert pKodList;
            if(removedKODs != null && removedKODs.size() > 0) DELETE[SELECT Id FROM Placement_KOD__c 
                                                                     WHERE Placement_Content__c = :contentId 
                                                                     AND KOD__c IN :removedKODs];
        }catch(DMLException de){
            throw new AuraException(de.getMessage());
        }
        
        
    }

}